#!/usr/bin/env python3
"""Generate growler_ucsc_pair.gxwf.yml: KegAlign seeding, then UCSC's own pairwise pipeline.

    python3 assemble_ucsc.py            # write the document
    python3 assemble_ucsc.py --check    # fail if the committed document is stale
    python3 assemble_ucsc.py --self-test

⛔ EVERY STEP AFTER KEGALIGN IS A COMMAND FROM KENT'S OWN SCRIPTS, cited where it is built, and
`assert_ucsc_order` refuses a document whose chain/net steps are not wired in that order. Sources:
`src/hg/utils/automation/doBlastzChainNet.pl` (chaining, netting, liftOver chain, synNet, mafNet) and
`doRecipBest.pl` (the reciprocal-best net), kent @d4e9b27.

  lastz -> lav                  growler_lastz_lav: one target per call (LAV refuses [multiple])
  lavToPsl                      doBlastzChainNet.pl: blastz-run-ucsc -outFormat psl
  axtChain -psl -scoreScheme=Q -minScore -linearGap | chainAntiRepeat        (line 809-813)
  chainMergeSort                                                             (line 889)
  chainPreNet | chainNet -minSpace=1 | netSyntenic -> noClass.net            (line 1012-1014)
  netChainSubset noClass.net all.chain | chainStitchId -> over.chain        (line 1017-1018)
  netFilter -syn | netToAxt | axtSort | axtToMaf -> synNet maf               (line 1861-1870;
      netToAxt reads over.chain rather than all.chain -- identical output, see build())
  doRecipBest.pl: over.chain | chainStitchId | chainSwap | chainSort; chainPreNet |
      chainNet -minSpace=1 -minScore=0 | netSyntenic; netChainSubset | chainStitchId; chainSwap |
      chainSort; chainPreNet | chainNet -minSpace=1 -minScore=0 | netSyntenic  (line 144-171)
  netToAxt rbest.net rbest.chain | axtSort | axtToMaf -> rbest maf           (line 252-258)

▶ UCSC'S PER-PAIR CHOICES ARE INPUTS, with UCSC's script defaults: hspthresh (K), gappedthresh (L),
ydrop (Y), xdrop (X), inner (H), masking (M), notransition (T=2), chain_min_score (1000, axtChain's
own), and the gap-cost table as a DATASET -- axtChain's loose/medium choice is a conditional, which a
workflow cannot connect, but its file form can be. gap/{loose,medium}.lineargap are kent's
gapCalc.c tables verbatim, measured to give chains byte-identical to the built-in presets.

⚠ FLAT: no nested subworkflow. vgp answers 500 to any update of a stored workflow that embeds one,
and a flat document maps over the pair-file collection at a single level.
⚠ KNOWN, INHERENT DIVERGENCES: seeding and ungapped extension are KegAlign's, not lastz's; and
lastz's dynamic masking (M) therefore acts only in the gapped stage.
"""
from __future__ import annotations

import argparse
import copy
import json
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from assemble import _sizes, IUC, TOOLS  # noqa: E402,I202 -- the shared tool table is the point

GROWLER = HERE / "growler.gxwf.yml"
OUT = HERE / "growler_ucsc_pair.gxwf.yml"
BANNER = "# GENERATED by assemble_ucsc.py -- DO NOT EDIT BY HAND. Edit assemble_ucsc.py and rerun.\n"

UCSC_TOOLS = {
    **TOOLS,
    "lastz_lav": "gt-growler-lastz-lav",
    "lavtopsl": "gt-ucsc-lavtopsl",
    "axtsort": "gt-ucsc-axtsort",
    "chainantirepeat": f"{IUC}/ucsc_chainantirepeat/ucsc_chainantirepeat/482+galaxy0",
    "netsyntenic": f"{IUC}/ucsc_netsyntenic/ucsc_netsyntenic/482+galaxy0",
    "netfilter": f"{IUC}/ucsc_netfilter/ucsc_netfilter/482+galaxy0",
    "nettoaxt": f"{IUC}/ucsc_nettoaxt/ucsc_nettoaxt/482+galaxy0",
    "axttomaf": f"{IUC}/ucsc_axttomaf/ucsc_axtomaf/482+galaxy1",
}

#: Workflow inputs: (type, default, doc). Defaults are lastz's / doBlastzChainNet.pl's own.
PARAMS = {
    "hspthresh": ("integer", 3000, "blastz K. lastz default 3000."),
    "gappedthresh": ("integer", 3000, "blastz L; lastz default L=K. Fed to BOTH stages."),
    "xdrop": ("integer", 910, "blastz X. lastz's default is 10 x the matrix's A/A score."),
    "ydrop": ("integer", 9430, "blastz Y. lastz's default is O + 300E for the matrix used. Fed to BOTH stages."),
    "inner": ("integer", 0, "blastz H; 0 is off. UCSC hg38 x panTro6: 2000."),
    "masking": ("integer", 0, "blastz M; 0 is off. Acts in the gapped stage only (KegAlign seeds)."),
    "notransition": ("boolean", False, "blastz T=2 is 12of19 with --notransition."),
    "noentropy": ("boolean", False, "blastz P=1 (entropy on) is the default."),
    "chain_min_score": ("integer", 1000, "axtChain -minScore. doBlastzChainNet.pl's default is axtChain's own, 1000."),
    "batch_lines": ("integer", 1000000, "KegAlign segment lines per element; 0 is one element per chromosome pair."),
    "num_gpu": ("integer", 1, "KegAlign GPUs. The tool default, -1, means every GPU on the node."),
}
DATA = {
    "target_fasta": "Target genome, soft-masked FASTA.",
    "query_fasta": "Query genome, soft-masked FASTA.",
    "target_sizes": "Target chromosome sizes (name<TAB>length).",
    "query_sizes": "Query chromosome sizes.",
    "scores": "lastz scoring matrix, uploaded as tabular: KegAlign and lastz read it as text, axtChain as tabular.",
    "linear_gap": "axtChain gap-cost table: gap/loose.lineargap (chicken-human) or gap/medium.lineargap (mouse-human and closer).",
}
_NETS = {"minFill": None, "inclHap": False, "verbose": None}


def _net(chain: str, t: str, q: str, label: str, min_score) -> dict:
    """chainNet -minSpace=1 [-minScore=...] on target/query sizes t,q -- fresh dicts every call."""
    i, s = _sizes(t, q)
    return {"tool_id": UCSC_TOOLS["chainnet"], "label": label, "in": {"in_chain": chain, **i},
            "state": {**s, "minSpace": 1, "minScore": min_score, **_NETS}}


def _prenet(chain: str, t: str, q: str, label: str) -> dict:
    i, s = _sizes(t, q)
    return {"tool_id": UCSC_TOOLS["chainprenet"], "label": label, "in": {"in_chain": chain, **i},
            "state": {**s, "pad": None, "inclHap": False}}


def _step(tool: str, label: str, inputs: dict, state: dict | None = None) -> dict:
    d = {"tool_id": UCSC_TOOLS[tool], "label": label, "in": inputs}
    if state is not None:
        d["state"] = state
    return d


def _to_maf(prefix: str, net: str, chain: str) -> dict:
    """netToAxt | axtSort | axtToMaf, as doBlastzChainNet.pl builds every MAF it ships."""
    _i, s = _sizes("target_sizes", "query_sizes")
    return {
        f"{prefix}_axt": _step("nettoaxt", f"{prefix}_axt", {"in_net": net, "in_chain": chain,
                               "in_target": "kegalign/target_2bit", "in_query": "kegalign/query_2bit"},
                               {"qChain": False, "maxGap": None, "noSplit": False}),
        f"{prefix}_sorted": _step("axtsort", f"{prefix}_sorted", {"input": f"{prefix}_axt/out"}),
        f"{prefix}_maf": _step("axttomaf", f"{prefix}_maf",
                               {"in_axt": f"{prefix}_sorted/output",
                                "target_reference_index_source|in_tar_ref_index": "target_sizes",
                                "query_reference_index_source|in_que_ref_index": "query_sizes"},
                               {**s, "t_prefix": None, "q_prefix": None, "score": False, "scoreZero": False}),
    }


def build(growler: dict) -> dict:
    kegalign = copy.deepcopy(growler["steps"]["kegalign"])
    kegalign.pop("position", None)
    kegalign["in"] = {
        "target": "target_fasta", "query": "query_fasta", "scoring_options|scoring": "scores",
        "seeding_options|notransition": "notransition",
        "ungapped_extension_options|hspthresh": "hspthresh",
        "ungapped_extension_options|xdrop": "xdrop",
        "ungapped_extension_options|noentropy": "noentropy",
        "gapped_extension_options|gappedthresh": "gappedthresh",
        "gapped_extension_options|ydrop": "ydrop",
        "batch_lines": "batch_lines", "system_options|num_gpu": "num_gpu"}
    st = kegalign["state"]
    st.pop("batch_lines", None)
    st["gapped_extension_options"] = {"notrivial": False}
    st["system_options"]["debug"] = True
    st["seeding_options"]["step"] = 1

    steps = {"kegalign": kegalign}
    steps["lastz_lav"] = _step("lastz_lav", "lastz_lav", {
        "pair": "kegalign/pairs", "target": "kegalign/target_2bit", "query": "kegalign/query_2bit",
        "scores": "scores", "gappedthresh": "gappedthresh", "ydrop": "ydrop", "inner": "inner",
        "masking": "masking"})
    steps["lavtopsl"] = _step("lavtopsl", "lavtopsl", {"input": "lastz_lav/output"})
    steps["axtchain"] = _step("axtchain", "axtchain", {
        "in_aln": "lavtopsl/output", "in_target": "kegalign/target_2bit",
        "in_query": "kegalign/query_2bit", "scoreScheme": "scores", "minScore": "chain_min_score",
        "linear_gap_options|lineargap_input": "linear_gap"},
        {"linear_gap_options": {"linear_gap": "linear_gap_file"}, "details_output": False})
    steps["chainantirepeat"] = _step("chainantirepeat", "chainantirepeat", {
        "in_chain": "axtchain/out", "in_target": "kegalign/target_2bit",
        "in_query": "kegalign/query_2bit"}, {"minScore": None, "noCheckScore": None})
    steps["chainmergesort"] = _step("chainmergesort", "chainmergesort",
                                    {"in_chains": "chainantirepeat/out"})
    # --- the net, the liftOver chain (doBlastzChainNet.pl 1012-1018)
    steps["prenet"] = _prenet("chainmergesort/out", "target_sizes", "query_sizes", "prenet")
    steps["net"] = _net("prenet/out", "target_sizes", "query_sizes", "net", None)
    steps["netsyntenic"] = _step("netsyntenic", "netsyntenic", {"in_net": "net/targetNet"})
    steps["over_subset"] = _step("netchainsubset", "over_subset",
                                 {"in_net": "netsyntenic/out", "in_chain": "chainmergesort/out"},
                                 {"splitOnInsert": False, "wholeChains": False, "skipMissing": False})
    steps["over_chain"] = _step("chainstitchid", "over_chain", {"input": "over_subset/out"})
    # --- synNet and its MAF (1861-1870)
    steps["syn_net"] = _step("netfilter", "syn_net", {"in_net": "netsyntenic/out"},
                             {"synteny": {"syn_filter": "filtersyn", "syntype": "-syn",
                                          "minSynScore": None, "minSynSize": None, "minSynAli": None},
                              "minGap": None})
    # ⛔ THE SYNNET MAF READS over.chain, NOT all.chain -- the one deliberate departure from
    # doBlastzChainNet.pl (line 1867), which hands netToAxt the full chain file. netToAxt loads every
    # chain it is given; all.chain is 7.6 GB for cs10 x 79X, and the job was OOM-killed on vgp (and at
    # a 12 GB cap locally). over.chain is netChainSubset(noClass.net, all.chain) | chainStitchId, and a
    # synNet's fills are a subset of the net's, so it holds every chain part netToAxt can look up.
    # Measured byte-identical AXT: hg38 x panTro6 chr21 (1,727 blocks) and cs10 x EH23a.chr1 (31,346
    # blocks, peak 2.6 -> 0.48 GB); cs10 x 79X now runs in 1.6 GB from a 42 MB chain file.
    steps.update(_to_maf("synnet", "syn_net/out", "over_chain/output"))
    # --- doRecipBest.pl 144-171
    steps["rb_stitch1"] = _step("chainstitchid", "rb_stitch1", {"input": "over_chain/output"})
    steps["rb_swap1"] = _step("chainswap", "rb_swap1", {"in_chain": "rb_stitch1/output"})
    steps["rb_sort1"] = _step("chainsort", "rb_sort1", {"in_chain": "rb_swap1/out"}, {"sort_by": ""})
    steps["rb_prenet_q"] = _prenet("rb_sort1/out", "query_sizes", "target_sizes", "rb_prenet_q")
    steps["rb_net_q"] = _net("rb_prenet_q/out", "query_sizes", "target_sizes", "rb_net_q", 0)
    steps["rb_syn_q"] = _step("netsyntenic", "rb_syn_q", {"in_net": "rb_net_q/targetNet"})
    steps["rb_subset"] = _step("netchainsubset", "rb_subset",
                               {"in_net": "rb_syn_q/out", "in_chain": "rb_sort1/out"},
                               {"splitOnInsert": False, "wholeChains": False, "skipMissing": False})
    steps["rb_stitch2"] = _step("chainstitchid", "rb_stitch2", {"input": "rb_subset/out"})
    steps["rb_swap2"] = _step("chainswap", "rb_swap2", {"in_chain": "rb_stitch2/output"})
    steps["rb_chain"] = _step("chainsort", "rb_chain", {"in_chain": "rb_swap2/out"}, {"sort_by": ""})
    steps["rb_prenet_t"] = _prenet("rb_chain/out", "target_sizes", "query_sizes", "rb_prenet_t")
    steps["rb_net_t"] = _net("rb_prenet_t/out", "target_sizes", "query_sizes", "rb_net_t", 0)
    steps["rb_net"] = _step("netsyntenic", "rb_net", {"in_net": "rb_net_t/targetNet"})
    steps.update(_to_maf("rbest", "rb_net/out", "rb_chain/out"))

    inputs = {k: {"type": "data", "doc": v} for k, v in DATA.items()}
    inputs.update({k: {"type": t, "default": d, "doc": doc} for k, (t, d, doc) in PARAMS.items()})
    outputs = {
        "all_chain": {"outputSource": "chainmergesort/out", "doc": "hg38.panTro6.all.chain analogue"},
        "net": {"outputSource": "netsyntenic/out", "doc": "noClass.net"},
        "over_chain": {"outputSource": "over_chain/output", "doc": "the liftOver chain"},
        "syn_net": {"outputSource": "syn_net/out"},
        "synnet_maf": {"outputSource": "synnet_maf/out", "doc": "multiz input for close genomes"},
        "rbest_chain": {"outputSource": "rb_chain/out"},
        "rbest_net": {"outputSource": "rb_net/out"},
        "rbest_maf": {"outputSource": "rbest_maf/out", "doc": "multiz input for other genomes"},
        "lav": {"outputSource": "lastz_lav/output", "doc": "per-element LAV, kept: the raw alignment record"},
    }
    return with_connected_values(
        {"class": "GalaxyWorkflow", "label": "Growler UCSC pair (KegAlign + UCSC chain/net, flat)",
         "doc": "One genome pair: KegAlign seeding, then kent's doBlastzChainNet.pl and doRecipBest.pl "
                "steps. See assemble_ucsc.py for the line-by-line provenance.",
         "inputs": inputs, "outputs": outputs, "steps": steps})


CONNECTED = {"__class__": "ConnectedValue"}


def with_connected_values(doc: dict) -> dict:
    """Mark every connected tool input `ConnectedValue` in the step's state, as Galaxy's editor does.

    ⛔ WITHOUT IT THE EDITOR WARNS ON EVERY CONNECTION. gxformat2 does not add the placeholder for an
    `in:` connection, so the stored tool state has no value there, and opening the workflow lists
    "No value found for ... Using default" for all 118 connections (vgp, 2026-09-28) -- harmless to a
    run, where the connection supplies the value, but alarming to anyone reading it. A `section|param`
    key is nested as Galaxy nests it. `unmarked_connections` is the check.
    """
    for st in doc["steps"].values():
        if st.get("state") is None:
            st["state"] = {}
        for key in st["in"]:
            *path, leaf = key.split("|")
            node = st["state"]
            for part in path:
                node = node.setdefault(part, {})
            node[leaf] = dict(CONNECTED)
    return doc


def unmarked_connections(doc: dict) -> list[str]:
    bad = []
    for name, st in doc["steps"].items():
        for key in st["in"]:
            node = st.get("state") or {}
            for part in key.split("|"):
                node = node.get(part) if isinstance(node, dict) else None
            if node != CONNECTED:
                bad.append(f"{name}.{key}")
    return bad


CHAIN_OUT = HERE / "growler_ucsc_chain.gxwf.yml"
#: The chain-only document keeps these of PARAMS; the rest drive seeding and lastz, which it skips.
CHAIN_PARAMS = ("chain_min_score",)


def build_chain_only(full: dict) -> dict:
    """growler_ucsc_pair from axtChain onward, reading a COLLECTION of existing alignments.

    ▶ For parameter sweeps and for alignments computed elsewhere. Derived from `full`, never written:
    the seeding and lastz steps are removed and their outputs rewired to inputs, so every chain/net
    step is the pair document's own, and `assert_chain_arm_identical` proves it.
    axtChain takes AXT or PSL, so the collection may be either.
    """
    doc = copy.deepcopy(full)
    doc["label"] = "Growler UCSC chain/net (from existing alignments, flat)"
    for k in ("kegalign", "lastz_lav", "lavtopsl"):
        del doc["steps"][k]
    rewire = {"kegalign/target_2bit": "target_2bit", "kegalign/query_2bit": "query_2bit",
              "lavtopsl/output": "alignments"}
    for st in doc["steps"].values():
        st["in"] = {k: rewire.get(v, v) for k, v in st["in"].items()}
    keep = {k: v for k, v in doc["inputs"].items() if k in DATA and k not in ("target_fasta", "query_fasta")}
    keep.update({k: doc["inputs"][k] for k in CHAIN_PARAMS})
    doc["inputs"] = {"alignments": {"type": "collection", "collection_type": "list",
                                    "doc": "AXT or PSL, one element per piece (e.g. growler_lastz output)."},
                     "target_2bit": {"type": "data"}, "query_2bit": {"type": "data"}, **keep}
    del doc["outputs"]["lav"]
    return doc


def assert_chain_arm_identical(full: dict, chain: dict) -> list[str]:
    """Every step the chain-only document has must equal the pair document's, up to the rewiring."""
    rewire = {"kegalign/target_2bit": "target_2bit", "kegalign/query_2bit": "query_2bit",
              "lavtopsl/output": "alignments"}
    bad = []
    for name, st in chain["steps"].items():
        ref = copy.deepcopy(full["steps"][name])
        ref["in"] = {k: rewire.get(v, v) for k, v in ref["in"].items()}
        if ref != st:
            bad.append(name)
    missing = set(full["steps"]) - set(chain["steps"]) - {"kegalign", "lastz_lav", "lavtopsl"}
    return bad + [f"missing {m}" for m in sorted(missing)]


#: (step, input, must read from) -- the wiring that makes this UCSC's pipeline and not a lookalike.
UCSC_ORDER = [
    ("lavtopsl", "input", "lastz_lav/output"),
    ("axtchain", "in_aln", "lavtopsl/output"),
    ("chainantirepeat", "in_chain", "axtchain/out"),
    ("chainmergesort", "in_chains", "chainantirepeat/out"),
    ("prenet", "in_chain", "chainmergesort/out"),
    ("net", "in_chain", "prenet/out"),
    ("netsyntenic", "in_net", "net/targetNet"),
    ("over_subset", "in_net", "netsyntenic/out"),
    ("over_subset", "in_chain", "chainmergesort/out"),   # all.chain, NOT the pre-netted chain
    ("syn_net", "in_net", "netsyntenic/out"),
    ("synnet_axt", "in_chain", "over_chain/output"),   # see build(): identical output, bounded memory
    ("rb_stitch1", "input", "over_chain/output"),
    ("rb_net_q", "in_chain", "rb_prenet_q/out"),
    ("rb_subset", "in_chain", "rb_sort1/out"),
    ("rb_prenet_t", "in_chain", "rb_chain/out"),
    ("rbest_axt", "in_net", "rb_net/out"),
    ("rbest_axt", "in_chain", "rb_chain/out"),
]


def assert_ucsc_order(doc: dict) -> list[str]:
    return [f"{s}.{i} reads {doc['steps'].get(s, {}).get('in', {}).get(i)!r}, expected {want!r}"
            for s, i, want in UCSC_ORDER if doc["steps"].get(s, {}).get("in", {}).get(i) != want]


def dangling(doc: dict) -> list[str]:
    known = set(doc["inputs"]) | set(doc["steps"])
    out = [f"{n}.{k} <- {v}" for n, s in doc["steps"].items() for k, v in s["in"].items()
           if v is None or v.split("/")[0] not in known]
    out += [f"output {k}" for k, v in doc["outputs"].items() if v["outputSource"].split("/")[0] not in known]
    return out


#: THE EDITOR LAYOUT (`layout`). Columns come from a topological sort; these say what the boxes are:
#: grey frames for UCSC's two scripts, numbered stage frames inside them titled with the commands and
#: kent line numbers, and yellow input groups down the left.
#: ⚠ Every step must sit in exactly one stage; `lane_problems` says which do not.
KENT = "kent @d4e9b27"
SCRIPTS = [("doBlastzChainNet.pl: align, chain, net, liftOver chain, synNet MAF", (1, 2, 3)),
           ("doRecipBest.pl: the reciprocal-best net and its MAF", (4, 5, 6))]
#: (number, title, colour, steps)
LANES = [
    (1, "Align and chain: KegAlign seeds on the GPU; lastz, one target per call; lavToPsl; "
        "axtChain -psl | chainAntiRepeat | chainMergeSort -> all.chain  (lines 809-889)", "blue",
     ["kegalign", "lastz_lav", "lavtopsl", "axtchain", "chainantirepeat", "chainmergesort"]),
    (2, "Net: chainPreNet | chainNet -minSpace=1 | netSyntenic -> noClass.net; "
        "netChainSubset | chainStitchId -> over.chain  (lines 1012-1018)", "green",
     ["prenet", "net", "netsyntenic", "over_subset", "over_chain"]),
    (3, "synNet MAF, the multiz input for close genomes: netFilter -syn | netToAxt | axtSort | axtToMaf  "
        "(lines 1861-1870)", "orange", ["syn_net", "synnet_axt", "synnet_sorted", "synnet_maf"]),
    (4, "Reciprocal best, query side: stitch and swap over.chain, net it with the query as reference  "
        "(lines 144-171)", "pink",
     ["rb_stitch1", "rb_swap1", "rb_sort1", "rb_prenet_q", "rb_net_q", "rb_syn_q", "rb_subset"]),
    (5, "Reciprocal best, target side: swap back and net again -> rbest.chain, rbest.net  (lines 144-171)",
     "pink", ["rb_stitch2", "rb_swap2", "rb_chain", "rb_prenet_t", "rb_net_t", "rb_net"]),
    (6, "Reciprocal-best MAF, the multiz input for other genomes: netToAxt | axtSort | axtToMaf  "
        "(lines 252-258)", "red", ["rbest_axt", "rbest_sorted", "rbest_maf"]),
]
#: Left column: inputs grouped by what they control, top to bottom; anything unlisted joins the last.
INPUT_GROUPS = [
    ("Genomes", ["target_fasta", "query_fasta", "target_2bit", "query_2bit", "alignments"]),
    ("Scoring", ["scores", "linear_gap", "chain_min_score"]),
    ("lastz / KegAlign parameters (UCSC's K L X Y H M T)",
     ["hspthresh", "gappedthresh", "xdrop", "ydrop", "inner", "masking", "notransition", "noentropy",
      "batch_lines", "num_gpu"]),
    ("Chromosome sizes (for the nets and MAFs)", ["target_sizes", "query_sizes"]),
]
#: Editor geometry, in Galaxy canvas pixels.
#: ROW is one terminal row: Galaxy lists every connected input and EVERY tool output, and labels such
#: as "Dataset with chrom sizes for query sequence. Typically a .fai file." wrap to 2-3 lines in its
#: 200 px (12.5rem) node, so a row is sized for two lines. Too big a frame is harmless; too small spills.
COL, WIDTH, GAP, HEAD, ROW, PAD, INPUT_H, TOP = 300, 220, 40, 44, 44, 30, 76, 230
#: Extra space between the inputs column and the first step column (layout).
GUTTER = 80


TERMINALS = HERE / "node_terminals.json"


def _wrapped(text: str, width: int) -> int:
    lines, cur = 1, 0
    for word in text.split():
        if cur and cur + 1 + len(word) > width:
            lines, cur = lines + 1, len(word)
        else:
            cur += (1 if cur else 0) + len(word)
    return lines


def node_height(step: dict, used_outputs: int) -> int:
    """A step's height in the editor, from the labels it shows when they are known, else ROW per row.

    ▶ From node_terminals.json (what vgp's editor lists for this tool): each label word-wrapped at
    the node's width (~25 characters an input line, ~20 an output line beside its buttons), 19.5 px
    a line, plus 10%. Used only when the step connects as many inputs as the snapshot shows.
    """
    known = json.loads(TERMINALS.read_text(encoding="utf-8"))["tools"].get(step["tool_id"]) if TERMINALS.exists() else None
    if not known or len(known["inputs"]) != len(step["in"]):
        return HEAD + ROW * (len(step["in"]) + max(2, used_outputs + 1))
    px = (32 + sum(6 + 19.5 * _wrapped(t, 25) for t in known["inputs"]) + 10
          + sum(8 + 19.5 * _wrapped(t, 20) for t in known["outputs"]) + 10)
    return int(px * 1.1)


def lane_problems(doc: dict, partial: bool = False) -> list[str]:
    """Steps in no stage or two; with `partial` (the chain-only document) a stage may name absent steps."""
    placed = [n for *_, names in LANES for n in names]
    return ([f"{n} is in no lane" for n in doc["steps"] if n not in placed]
            + [f"{n} is in a lane but not a step" for n in placed if n not in doc["steps"] and not partial]
            + [f"{n} is in two lanes" for n in sorted({n for n in placed if placed.count(n) > 1})])


def layout(doc: dict, max_band: int = 9) -> dict:
    """A copy of `doc` placed by a topological sort for x and the hand-drawn STAGES for y and frames.

    Column: a step sits one past its deepest source; an input one before its FIRST consumer, so a
    shared input (sizes, scores) waits beside the stage that needs it. The columns are wrapped into
    bands, read like lines of text, of at most `max_band` columns, and never inside a stage. Within a band each stage of
    LANES gets its own track and frame, so the boxes never overlap; a stage that wraps continues in
    a second frame marked (cont.). Inputs are the yellow track at the top.
    """
    d = copy.deepcopy(doc)
    src = {n: [v.split("/")[0] for v in s["in"].values()] for n, s in d["steps"].items()}
    outs: dict[str, set] = {n: set() for n in d["steps"]}
    users: dict[str, list] = {n: [] for n in [*d["inputs"], *d["steps"]]}
    for n, s in d["steps"].items():
        for v in s["in"].values():
            users[v.split("/")[0]].append(n)
            if "/" in v:
                outs[v.split("/")[0]].add(v.split("/", 1)[1])
    layer: dict[str, int] = {}
    todo = dict(src)
    while todo:                                           # Kahn's algorithm, over the steps
        ready = [n for n, ss in todo.items() if all(s in layer or s in d["inputs"] for s in ss)]
        if not ready:
            raise SystemExit(f"cycle among {sorted(todo)}")
        for n in ready:
            layer[n] = 1 + max((layer[s] for s in src[n] if s in layer), default=-1)
            del todo[n]

    def height(n: str) -> int:
        if n in d["inputs"]:
            return INPUT_H - 8
        return node_height(d["steps"][n], len(outs[n]))

    # ▶ x from the sort; y from the STAGE: within a band every stage of LANES gets its own track, so
    # each stage's frame is a clean box, and a stage that wraps gets a second frame marked (cont.).
    # Column 0 of a band holds the inputs whose first consumer is in it, grouped as INPUT_GROUPS.
    stage, meta = {}, {}
    for num, title, colour, names in LANES:
        meta[num] = (f"{num}  {title}", colour)
        stage.update({n: num for n in names if n in d["steps"]})
    # ▶ A STAGE IS NEVER SPLIT: it joins the current band if all its columns fit, else it opens the
    # next band with its first column there. Parallel stages (3 beside 4) make every fixed wrap
    # point cut one of them; this keeps each stage's frame whole.
    span: dict[int, tuple] = {}
    for n, st in stage.items():
        lo, hi = span.get(st, (layer[n], layer[n]))
        span[st] = (min(lo, layer[n]), max(hi, layer[n]))
    starts, band_of_stage = [], {}
    for st in sorted(span, key=lambda k: span[k]):
        lo, hi = span[st]
        if not starts or hi - starts[-1] >= max_band:
            starts.append(lo)
        band_of_stage[st] = len(starts) - 1
    n_bands = len(starts)
    band_of = {n: band_of_stage[stage[n]] for n in d["steps"]}
    col_of = {n: layer[n] - starts[band_of[n]] for n in d["steps"]}
    per_band = max(col_of.values()) + 1
    first = {n: min((band_of[u] for u in users[n]), default=0) for n in d["inputs"]}
    group_of = {n: t for t, ns in INPUT_GROUPS for n in ns}
    cells: dict[tuple, list] = {}                          # (band, stage, column) -> steps
    for n in d["steps"]:
        cells.setdefault((band_of[n], stage[n], 1 + col_of[n]), []).append(n)

    script_of = {num: t for t, nums in SCRIPTS for num in nums}
    # ▶ Script frames are stacked GUTTER apart -- the same space as between the inputs column and the
    # first step column -- and the inputs column runs down the left on its own, so a tall input
    # group never pushes the next band down.
    y, frames, outer, seen, seen_script, band_top = TOP, [], [], set(), set(), {}
    for band in range(n_bands):
        band_top[band], current, boxes = y, None, []
        for st in sorted({k[1] for k in cells if k[0] == band}):
            if script_of.get(st) != current:              # a new script frame opens: leave its header
                if boxes:
                    outer.append((current, boxes))
                    y = boxes[-1][1] + boxes[-1][3] + PAD // 2 + GUTTER
                current, boxes = script_of.get(st), []
                y += HEAD + PAD // 2
            mine = {c: ns for (bb, ss, c), ns in cells.items() if bb == band and ss == st}
            tall = max(sum(height(n) + GAP // 2 for n in ns) for ns in mine.values()) - GAP // 2
            for c, ns in mine.items():
                ty = y + PAD + HEAD
                for n in ns:
                    d["steps"][n]["position"] = {"left": GUTTER + COL * c, "top": ty}
                    ty += height(n) + GAP // 2
            lo, hi = min(mine), max(mine)
            title, colour = meta[st]
            box = [GUTTER + COL * lo - PAD, y, COL * (hi - lo) + WIDTH + 2 * PAD, tall + HEAD + 2 * PAD]
            boxes.append(box)
            frames.append({"type": "frame", "position": box[:2], "size": box[2:],
                           "color": colour, "title": title + ("  (cont.)" if st in seen else "")})
            seen.add(st)
            y += box[3] + GAP // 2
        if boxes:
            outer.append((current, boxes))
            y = boxes[-1][1] + boxes[-1][3] + PAD // 2 + GUTTER
    iy = TOP
    for band in range(n_bands):                            # each group starts no higher than its band
        for gtitle, _ in [*INPUT_GROUPS, ("Inputs", [])]:
            ns = [n for n in d["inputs"] if first[n] == band and group_of.get(n, "Inputs") == gtitle]
            if not ns:
                continue
            iy = max(iy, band_top[band])
            for i, n in enumerate(ns):
                d["inputs"][n]["position"] = {"left": 0, "top": iy + HEAD + PAD + INPUT_H * i}
            h = HEAD + 2 * PAD + INPUT_H * len(ns)
            frames.append({"type": "frame", "position": [-PAD, iy], "size": [WIDTH + 2 * PAD, h],
                           "color": "yellow", "title": gtitle})
            iy += h + GAP // 2
    scripts = []
    for title, boxes in outer:                             # one frame per script per band, around its stages
        x0 = min(bx[0] for bx in boxes) - PAD // 2
        y0 = min(bx[1] for bx in boxes) - HEAD - PAD // 2
        x1 = max(bx[0] + bx[2] for bx in boxes) + PAD // 2
        y1 = max(bx[1] + bx[3] for bx in boxes) + PAD // 2
        # black is Galaxy's palette's nearest to grey: a frame is a faint tint, so it reads as light grey
        scripts.append({"type": "frame", "position": [x0, y0], "size": [x1 - x0, y1 - y0], "color": "black",
                        "title": f"{title}  ({KENT})" + ("  (cont.)" if title in seen_script else "")})
        seen_script.add(title)
    d["comments"] = [{"type": "markdown", "position": [0, 0], "size": [COL * (per_band + 1), TOP - GAP],
                      "color": "none", "text": f"## {d['label']}\n\n{NOTE}"}] + scripts + frames
    return d


NOTE = f"""**How to read this workflow.** Columns follow a topological sort of the steps, wrapped into
bands read like lines of text, with the inputs in yellow down the left; the grey outer frames are UCSC's
two scripts, and each numbered frame inside is one stage. Everything after KegAlign is a command from UCSC's own scripts, wired in their order
({KENT}): **blue, green, orange** are `doBlastzChainNet.pl`, **pink, red** are `doRecipBest.pl`; the
frame titles give the commands and script line numbers. The orange and red MAFs are the multiz
inputs: synNet for close genomes, reciprocal best for the rest. Generated by galaxytools
`workflows/growler/assemble_ucsc.py`, which asserts this wiring."""


def self_test() -> int:
    doc = build(yaml.safe_load(GROWLER.read_text(encoding="utf-8")))
    fails = 0

    def check(name: str, cond: bool) -> None:
        nonlocal fails
        fails += not cond
        print(f"  {'ok ' if cond else 'FAIL'} {name}")

    check("no dangling connection", dangling(doc) == [])
    check("every connection is marked ConnectedValue", unmarked_connections(doc) == [])
    unmarked = copy.deepcopy(doc)
    unmarked["steps"]["prenet"]["state"]["target_reference_index_source"].pop("in_tar_ref_index")
    check("  and an unmarked nested connection is caught",
          unmarked_connections(unmarked) == ["prenet.target_reference_index_source|in_tar_ref_index"])
    check("wired in UCSC's order", assert_ucsc_order(doc) == [])
    check("no nested subworkflow", not any("run" in s for s in doc["steps"].values()))
    nets = {k: doc["steps"][k]["state"] for k in ("net", "rb_net_q", "rb_net_t")}
    check("both reciprocal-best nets use -minSpace=1 -minScore=0",
          all(nets[k]["minSpace"] == 1 and nets[k]["minScore"] == 0 for k in ("rb_net_q", "rb_net_t")))
    check("the main net uses -minSpace=1 and no minScore",
          nets["net"]["minSpace"] == 1 and nets["net"]["minScore"] is None)
    keg, lz, ax = doc["steps"]["kegalign"]["in"], doc["steps"]["lastz_lav"]["in"], doc["steps"]["axtchain"]
    check("gappedthresh and ydrop reach BOTH stages",
          keg.get("gapped_extension_options|gappedthresh") == "gappedthresh"
          and keg.get("gapped_extension_options|ydrop") == "ydrop"
          and lz["gappedthresh"] == "gappedthresh" and lz["ydrop"] == "ydrop")
    check("axtChain reads PSL, the scoring matrix, and the gap file",
          ax["in"]["in_aln"] == "lavtopsl/output" and ax["in"]["scoreScheme"] == "scores"
          and ax["state"]["linear_gap_options"]["linear_gap"] == "linear_gap_file")
    bad = copy.deepcopy(doc)
    bad["steps"]["over_subset"]["in"]["in_chain"] = "prenet/out"
    check("  and netChainSubset on the PRE-NETTED chain is caught", assert_ucsc_order(bad) != [])
    for g in ("loose", "medium"):
        check(f"gap/{g}.lineargap is present", (HERE / "gap" / f"{g}.lineargap").exists())
    chain = build_chain_only(doc)
    check("every step sits in exactly one layout stage", lane_problems(doc) == [])
    stray = copy.deepcopy(doc)
    stray["steps"]["extra"] = stray["steps"]["lavtopsl"]
    check("  and a step in no stage is caught", lane_problems(stray) == ["extra is in no lane"])
    placed = layout(doc)
    nodes = [*placed["inputs"].values(), *placed["steps"].values()]
    check("layout places every input and step", all("position" in n for n in nodes))
    check("layout changes nothing but positions and comments",
          {k: v for k, v in placed.items() if k != "comments"} == {**doc, "steps": {
              n: {**st, "position": placed["steps"][n]["position"]} for n, st in doc["steps"].items()},
              "inputs": {n: {**i, "position": placed["inputs"][n]["position"]} for n, i in doc["inputs"].items()}})
    check("chain-only: no dangling connection", dangling(chain) == [])
    check("chain-only: every step identical to the pair document's", assert_chain_arm_identical(doc, chain) == [])
    check("chain-only: axtChain reads the alignments collection", chain["steps"]["axtchain"]["in"]["in_aln"] == "alignments")
    tampered = copy.deepcopy(chain)
    tampered["steps"]["net"]["state"]["minSpace"] = 25
    check("  and a drifted chain step is caught", assert_chain_arm_identical(doc, tampered) == ["net"])
    if OUT.exists():
        committed = yaml.safe_load(OUT.read_text(encoding="utf-8"))
        check("the committed document matches a fresh build", committed == layout(doc))
    if CHAIN_OUT.exists():
        check("the committed chain-only document matches",
              yaml.safe_load(CHAIN_OUT.read_text(encoding="utf-8")) == layout(chain))
    print("\nall tests passed" if not fails else f"\n{fails} FAILED")
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    doc = build(yaml.safe_load(GROWLER.read_text(encoding="utf-8")))
    problems = dangling(doc) + assert_ucsc_order(doc) + unmarked_connections(doc) + lane_problems(doc)
    if problems:
        sys.exit("REFUSING:\n  " + "\n  ".join(problems))
    chain = build_chain_only(doc)
    problems = assert_chain_arm_identical(doc, chain) + dangling(chain)
    if problems:
        sys.exit("REFUSING the chain-only document:\n  " + "\n  ".join(problems))
    # positions are applied last, to what is written; every check above ran on the unplaced documents
    for path, d in ((OUT, layout(doc)), (CHAIN_OUT, layout(chain))):
        if a.check:
            if not path.exists() or yaml.safe_load(path.read_text(encoding="utf-8")) != d:
                sys.exit(f"{path.name} is stale -- run assemble_ucsc.py and commit")
            print(f"{path.name} is current")
            continue
        path.write_text(BANNER + yaml.safe_dump(d, sort_keys=False, allow_unicode=True, width=100),
                        encoding="utf-8")
        print(f"wrote {path.name} ({len(d['steps'])} steps)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
