#!/usr/bin/env python3
"""Assemble the panel workflow by inlining Growler as a subworkflow.

    ./assemble_panel.py                 # writes growler_panel.gxwf.yml
    ./assemble_panel.py --check         # non-zero if the committed file is stale
    ./assemble_panel.py --self-test

⛔ THERE IS ONE SOURCE OF TRUTH AND IT IS `growler.gxwf.yml`. gxformat2 has no include: a
subworkflow step carries the whole child document inline under `run:`. Writing the panel workflow
by hand would mean a second copy of Growler that drifts from the first, which is the defect this
project already has four instances of (two scripts, four copies, in two repositories). So the
panel file is GENERATED, and `--check` fails the build if it stops matching.

▶ WHY THE PANEL CASE IS A SUBWORKFLOW AT ALL, rather than the same steps flattened:

Galaxy does not broadcast a dataset across nesting levels. Flattened, `growler_lastz` would have to
be mapped over the INNER (chromosome-pair) level while its 2bits sit at the OUTER (genome-pair)
level, and there is no native operation that expands one dataset across N identifiers -- brc-tools
works around this by materialising parallel `list:list` collections with matching identifiers.

Inside a Growler invocation there is only one level: one genome pair, two 2bits as plain `data`
inputs, a flat collection of kegs. The nesting problem does not get solved here, it stops existing.
And the outer `list:list` is produced for free: a subworkflow mapped over a list, emitting a
collection, yields `list:list` with outer identifiers preserved -- measured on usegalaxy.org 26.1
on 2026-09-17, in exactly this shape.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
GROWLER = HERE / "growler.gxwf.yml"
PANEL = HERE / "growler_panel.gxwf.yml"

BANNER = """# GENERATED by assemble_panel.py from growler.gxwf.yml -- DO NOT EDIT BY HAND.
# gxformat2 has no include directive, so the subworkflow is inlined. Edit growler.gxwf.yml and
# re-run ./assemble_panel.py; ./assemble_panel.py --check fails if this file is stale.
"""


def build(growler: dict) -> dict:
    """The panel workflow: every ordered genome pair, self-pairs dropped, Growler mapped over."""
    return {
        "class": "GalaxyWorkflow",
        "label": "Growler panel (every genome pair)",
        "doc": (
            "Runs Growler over every ordered pair of a genome collection.\n\n"
            "__CROSS_PRODUCT_FLAT__ emits two aligned flat lists; feeding output_a to the target\n"
            "input and output_b to the query input is how a pair reaches a two-input consumer\n"
            "natively -- Galaxy then matches them element-wise. __FILTER_FROM_FILE__ removes the\n"
            "diagonal, which is the N self-pairs an all-against-all grid always contains and which\n"
            "are meaningless to align.\n\n"
            "The output is list:list -- outer = genome pair, inner = chromosome pair -- with both\n"
            "identifiers preserved, so downstream steps can regroup on either axis.\n\n"
            "⚠ Job count is the scaling wall, not compute. For a panel of N genomes with C\n"
            "chromosomes this is N*(N-1) Growler invocations, each mapping LASTZ over roughly C^2\n"
            "kegs. Ten genomes of ten chromosomes is ~9,000 LASTZ jobs; fourteen chromosomes across\n"
            "ten genomes is ~17,600. That is Galaxy's scheduler and database, not the aligner."
        ),
        "inputs": {
            "genomes": {
                "type": "collection",
                "collection_type": "list",
                "doc": "Soft-masked genomes, one element per strain. These element identifiers "
                       "become the pair ids and, eventually, browser track names.",
                "position": {"top": 0, "left": 0},
            },
            "self_pairs": {
                "type": "data",
                "doc": "One 'X_X' line per strain. A file rather than a parameter because Galaxy "
                       "filters collections by matching identifiers against file CONTENT, and the "
                       "identifiers are only known once the panel is chosen.",
                "position": {"top": 150, "left": 0},
            },
            "scores": {
                "type": "data",
                "optional": True,
                "doc": "Scoring file in LASTZ format, shared by every pair.",
                "position": {"top": 260, "left": 0},
            },
        },
        "steps": {
            "pairs": {
                "tool_id": "__CROSS_PRODUCT_FLAT__",
                "label": "pairs",
                "in": {"input_a": "genomes", "input_b": "genomes"},
                "position": {"top": 0, "left": 260},
            },
            "targets": {
                "tool_id": "__FILTER_FROM_FILE__",
                "label": "targets",
                "in": {"input": "pairs/output_a", "how|filter_source": "self_pairs"},
                "state": {"how": {"how_filter": "remove_if_present"}},
                "position": {"top": 0, "left": 520},
            },
            "queries": {
                "tool_id": "__FILTER_FROM_FILE__",
                "label": "queries",
                "in": {"input": "pairs/output_b", "how|filter_source": "self_pairs"},
                "state": {"how": {"how_filter": "remove_if_present"}},
                "position": {"top": 160, "left": 520},
            },
            "growler": {
                "run": growler,
                "label": "growler",
                "doc": "Mapped over the pair lists. Each invocation sees one genome pair and "
                       "emits a flat keg collection; Galaxy nests those into list:list.",
                "in": {"target_fasta": "targets/output_filtered",
                       "query_fasta": "queries/output_filtered",
                       "scores": "scores"},
                "position": {"top": 0, "left": 800},
            },
        },
        "outputs": {
            "alignments": {"outputSource": "growler/alignments"},
        },
    }


def render(growler: dict) -> str:
    return BANNER + yaml.safe_dump(build(growler), sort_keys=False, width=100, allow_unicode=True)


def self_test() -> int:
    failures = []

    def check(label, got, want):
        if got != want:
            print(f"not ok - {label}\n     got: {got}\nexpected: {want}")
            failures.append(label)
        else:
            print(f"ok - {label}")

    child = {"class": "GalaxyWorkflow", "label": "kid",
             "inputs": {"target_fasta": {"type": "data"}, "query_fasta": {"type": "data"},
                        "scores": {"type": "data", "optional": True}},
             "outputs": {"alignments": {"outputSource": "x/out"}}, "steps": {}}
    panel = build(child)

    check("the child is inlined, not referenced", panel["steps"]["growler"]["run"], child)
    check("self-pairs are filtered out of both arms",
          sorted(k for k, v in panel["steps"].items() if v.get("tool_id") == "__FILTER_FROM_FILE__"),
          ["queries", "targets"])
    # ▶ output_a must reach the TARGET and output_b the QUERY. Crossing them silently aligns every
    # pair backwards: the run succeeds, the chains are all reversed, and nothing raises.
    check("output_a drives target", panel["steps"]["targets"]["in"]["input"], "pairs/output_a")
    check("output_b drives query", panel["steps"]["queries"]["in"]["input"], "pairs/output_b")
    # ⛔ THE FILTER DIRECTION. `self_pairs` lists the diagonal, so the diagonal must be REMOVED.
    # `remove_if_absent` keeps only what the file names -- i.e. only the self-pairs -- which is the
    # exact inverse, runs perfectly happily, and aligns every genome against itself. This assertion
    # exists because the first version of this file had it backwards.
    for arm in ("targets", "queries"):
        check(f"{arm}: the diagonal is removed, not retained",
              panel["steps"][arm]["state"]["how"]["how_filter"], "remove_if_present")

    check("growler takes the filtered lists, not the raw cross product",
          [panel["steps"]["growler"]["in"]["target_fasta"], panel["steps"]["growler"]["in"]["query_fasta"]],
          ["targets/output_filtered", "queries/output_filtered"])
    # every name the panel connects to must exist in the child, or the import binds nothing
    for slot in ("target_fasta", "query_fasta", "scores"):
        check(f"child declares input {slot}", slot in child["inputs"], True)
    check("child declares the output the panel exports",
          panel["outputs"]["alignments"]["outputSource"].split("/")[1] in child["outputs"], True)
    check("render round-trips through yaml",
          yaml.safe_load(render(child))["steps"]["growler"]["run"]["label"], "kid")

    if failures:
        print(f"\n{len(failures)} test(s) failed")
        return 1
    print("\nall tests passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    rendered = render(yaml.safe_load(GROWLER.read_text()))
    if args.check:
        if not PANEL.exists():
            print(f"{PANEL.name} is missing; run ./assemble_panel.py", file=sys.stderr)
            return 1
        if PANEL.read_text() != rendered:
            print(f"{PANEL.name} is stale; run ./assemble_panel.py", file=sys.stderr)
            return 1
        print(f"{PANEL.name} is current")
        return 0

    PANEL.write_text(rendered)
    print(f"wrote {PANEL.name} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
