#!/usr/bin/env python3
"""Generate growler_multiz.gxwf.yml: UCSC's multizNway recipe, from pairwise MAFs to one MAF per sequence.

    python3 assemble_multiz.py            # write the document
    python3 assemble_multiz.py --check    # fail if the committed document is stale
    python3 assemble_multiz.py --self-test

⛔ EVERY STEP IS A STEP OF UCSC'S OWN RECIPE, kent src/hg/makeDb/doc/hg38/multiz5way.txt (@d4e9b27):

  mafSplit -byTarget -useHashedName=8, per species       -> species -> bucket
  (the cluster run's layout, as a collection)             -> bucket -> species        Apply rules
  autoMultiz.csh: autoMZ + T= E=<ref> "<tree>" *.sing.maf -> one MAF per bucket       multiz_roast
  mafSplit -byTarget -useFullSequenceName                 -> bucket -> sequence
  (every sequence is in exactly one bucket)               -> one MAF per sequence     Apply rules

UCSC concatenates the buckets before the per-sequence split; splitting each bucket directly gives the
same per-sequence files, and a block lives in exactly one of them. Gap annotation (twoBitInfo -nBed,
mafAddIRows -nBeds) is the next stage and needs an XML mafAddIRows, which cannot be a UDT: it names each
species' BED, and element identifiers do not reach a UDT job.

▶ MEASURED: on laila with the tools as UDTs, this reproduces UCSC's recipe run by hand with the same
multiz build, on every non-comment line of all 7 reference sequences of hg38 multiz5way buckets
033/035/071/093 (chr21, chr22, chrX, chrM, three alts; invocation 63cd3858d057a6d1, 2026-09-29).
"""
from __future__ import annotations

import argparse
import copy
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from assemble import tool_version  # noqa: E402,I202 -- one implementation of the XML version rule

ROOT = HERE.parent.parent
OUT = HERE / "growler_multiz.gxwf.yml"
BANNER = "# GENERATED by assemble_multiz.py -- DO NOT EDIT BY HAND. Edit assemble_multiz.py and rerun.\n"
#: (UDT id, the XML whose version it carries). The workflow runs the UDT editions until the tools are
#: installed from the Tool Shed; the version is the wrapper's own either way.
TOOLS = {
    "mafsplit": ("gt-ucsc-mafsplit", "tools/ucsc_mafsplit/mafsplit.xml"),
    "roast": ("gt-multiz-roast", "tools/multiz_roast/multiz_roast.xml"),
}
APPLY_RULES = ("__APPLY_RULES__", "1.1.0")
UCSC_HASH_BITS = 8                      # mafSplit -useHashedName=8 in every hg38 multizNway build


def _tool(key: str) -> dict:
    tool_id, xml = TOOLS[key]
    return {"tool_id": tool_id, "tool_version": tool_version(ROOT / xml)}


def _rules(identifier_columns: list[str], mapping_columns: list[int]) -> dict:
    return {"rules": {"rules": [{"type": "add_column_metadata", "value": c} for c in identifier_columns],
                      "mapping": [{"type": "list_identifiers", "columns": mapping_columns}]}}


def build() -> dict:
    steps = {
        "split": {**_tool("mafsplit"), "doc": "mafSplit -byTarget -useHashedName=8, per species.",
                  "in": {"input": "pairwise"}, "state": {"hash_bits": UCSC_HASH_BITS}},
        "by_bucket": {"tool_id": APPLY_RULES[0], "tool_version": APPLY_RULES[1],
                      "doc": "species -> bucket becomes bucket -> species.",
                      "in": {"input": "split/pieces"},
                      "state": _rules(["identifier0", "identifier1"], [1, 0])},
        "roast": {**_tool("roast"), "doc": "autoMZ per bucket; each bucket's species list feeds the multiple input.",
                  "in": {"pairwise": "by_bucket/output", "tree": "tree", "reference": "reference"}},
        "split_sequences": {**_tool("mafsplit"), "doc": "mafSplit -byTarget -useFullSequenceName, per bucket.",
                            "in": {"input": "roast/output"}, "state": {"hash_bits": 0}},
        "by_sequence": {"tool_id": APPLY_RULES[0], "tool_version": APPLY_RULES[1],
                        "doc": "bucket -> sequence becomes a list by sequence; each sequence is in exactly one bucket.",
                        "in": {"input": "split_sequences/pieces"},
                        "state": _rules(["identifier1"], [0])},
    }
    return {
        "class": "GalaxyWorkflow",
        "label": "Growler multiz (UCSC multizNway, before gap annotation)",
        "doc": "UCSC's multizNway recipe (kent src/hg/makeDb/doc/hg38/multiz5way.txt) up to mafAddIRows: each "
               "species' pairwise MAF split into hashed buckets of reference sequences, regrouped by bucket, roast "
               "per bucket, and the result split into one MAF per reference sequence.",
        "inputs": {
            "pairwise": {"type": "collection", "collection_type": "list",
                         "doc": "One pairwise MAF per species, rows named species.sequence, reference on top, "
                                "sorted by reference position."},
            "tree": {"type": "data", "doc": "Species tree (Newick); branch lengths are ignored."},
            "reference": {"type": "string", "doc": "The reference's name, as it prefixes its rows (hg38 for hg38.chr1)."},
        },
        "outputs": {"per_sequence": {"outputSource": "by_sequence/output",
                                     "doc": "One multiple-alignment MAF per reference sequence, before mafAddIRows."}},
        "steps": steps,
    }


def recipe_problems(doc: dict) -> list[str]:
    """What would make this a different recipe than UCSC's, each named."""
    st = doc["steps"]
    want = {
        ("split", "hash_bits"): UCSC_HASH_BITS,
        ("split_sequences", "hash_bits"): 0,
    }
    out = [f"{s}.{k} is {st[s]['state'].get(k)!r}, UCSC's recipe needs {v!r}"
           for (s, k), v in want.items() if st[s]["state"].get(k) != v]
    if st["by_bucket"]["state"] != _rules(["identifier0", "identifier1"], [1, 0]):
        out.append("by_bucket does not swap species -> bucket into bucket -> species")
    if st["by_sequence"]["state"] != _rules(["identifier1"], [0]):
        out.append("by_sequence does not keep the sequence level alone")
    for s, src in (("by_bucket", "split/pieces"), ("roast", "by_bucket/output"),
                   ("split_sequences", "roast/output"), ("by_sequence", "split_sequences/pieces")):
        got = next(iter(st[s]["in"].values())) if s != "roast" else st[s]["in"]["pairwise"]
        if got != src:
            out.append(f"{s} reads {got!r}, the recipe needs {src!r}")
    return out


def dangling(doc: dict) -> list[str]:
    known = set(doc["inputs"]) | set(doc["steps"])
    out = [f"{n}.{k} <- {v}" for n, s in doc["steps"].items() for k, v in s["in"].items()
           if v.split("/")[0] not in known]
    out += [f"output {k}" for k, v in doc["outputs"].items() if v["outputSource"].split("/")[0] not in known]
    return out


def self_test() -> int:
    doc = build()
    fails = 0

    def check(name: str, cond: bool) -> None:
        nonlocal fails
        fails += not cond
        print(f"  {'ok ' if cond else 'FAIL'} {name}")

    check("no dangling connection", dangling(doc) == [])
    check("UCSC's recipe: buckets of 8 bits, swap, roast per bucket, per-sequence split", recipe_problems(doc) == [])
    for key, (tool_id, xml) in TOOLS.items():
        pins = {s["tool_version"] for s in doc["steps"].values() if s["tool_id"] == tool_id}
        check(f"{tool_id} pins the version {pathlib.Path(xml).name} declares", pins == {tool_version(ROOT / xml)})
    swapped = copy.deepcopy(doc)
    swapped["steps"]["by_bucket"]["state"] = _rules(["identifier0", "identifier1"], [0, 1])
    check("  and a regroup that does not swap is caught", recipe_problems(swapped) != [])
    whole = copy.deepcopy(doc)
    whole["steps"]["split"]["state"]["hash_bits"] = 0
    check("  and per-sequence splitting before roast is caught", recipe_problems(whole) != [])
    if OUT.exists():
        check("the committed document matches a fresh build", yaml.safe_load(OUT.read_text(encoding="utf-8")) == doc)
    print("\nall tests passed" if not fails else f"\n{fails} FAILED")
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    doc = build()
    problems = dangling(doc) + recipe_problems(doc)
    if problems:
        sys.exit("REFUSING:\n  " + "\n  ".join(problems))
    if a.check:
        if not OUT.exists() or yaml.safe_load(OUT.read_text(encoding="utf-8")) != doc:
            sys.exit(f"{OUT.name} is stale -- run assemble_multiz.py and commit")
        print(f"{OUT.name} is current")
        return 0
    OUT.write_text(BANNER + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8")
    print(f"wrote {OUT.name} ({len(doc['steps'])} steps)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
