#!/usr/bin/env python3
"""Generate growler_ucsc_pair.gxwf.yml: KegAlign seeding, then UCSC's own pairwise pipeline.

    python3 assemble_ucsc.py            # write the document
    python3 assemble_ucsc.py --check    # fail if the committed document is stale
    python3 assemble_ucsc.py --self-test

⛔ EVERY STEP AFTER KEGALIGN IS A COMMAND FROM KENT'S OWN SCRIPTS, cited where it is built, and
`assert_ucsc_order` refuses a document whose chain/net steps are not wired in that order. Sources:
`src/hg/utils/automation/doBlastzChainNet.pl` (chaining, netting, liftOver chain, synNet, mafNet) and
`doRecipBest.pl` (the reciprocal-best net), kent @d4e9b27.

  lastz -> lav                  growler_lastz_lav: one target per call (LAV refuses [multiple])
  lavToPsl                      doBlastzChainNet.pl: blastz-run-ucsc -outFormat psl
  axtChain -psl -scoreScheme=Q -minScore -linearGap | chainAntiRepeat        (line 809-813)
  chainMergeSort                                                             (line 889)
  chainPreNet | chainNet -minSpace=1 | netSyntenic -> noClass.net            (line 1012-1014)
  netChainSubset noClass.net all.chain | chainStitchId -> over.chain        (line 1017-1018)
  netFilter -syn | netToAxt | axtSort | axtToMaf -> synNet maf               (line 1861-1870;
      netToAxt reads over.chain rather than all.chain -- identical output, see build())
  doRecipBest.pl: over.chain | chainStitchId | chainSwap | chainSort; chainPreNet |
      chainNet -minSpace=1 -minScore=0 | netSyntenic; netChainSubset | chainStitchId; chainSwap |
      chainSort; chainPreNet | chainNet -minSpace=1 -minScore=0 | netSyntenic  (line 144-171)
  netToAxt rbest.net rbest.chain | axtSort | axtToMaf -> rbest maf           (line 252-258)

▶ UCSC'S PER-PAIR CHOICES ARE INPUTS, with UCSC's script defaults: hspthresh (K), gappedthresh (L),
ydrop (Y), xdrop (X), inner (H), masking (M), notransition (T=2), chain_min_score (1000, axtChain's
own), and the gap-cost table as a DATASET -- axtChain's loose/medium choice is a conditional, which a
workflow cannot connect, but its file form can be. gap/{loose,medium}.lineargap are kent's
gapCalc.c tables verbatim, measured to give chains byte-identical to the built-in presets.

⚠ FLAT: no nested subworkflow. vgp answers 500 to any update of a stored workflow that embeds one,
and a flat document maps over the pair-file collection at a single level.
⚠ KNOWN, INHERENT DIVERGENCES: seeding and ungapped extension are KegAlign's, not lastz's; and
lastz's dynamic masking (M) therefore acts only in the gapped stage.
"""
from __future__ import annotations

import argparse
import copy
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from assemble import _sizes, IUC, TOOLS  # noqa: E402,I202 -- the shared tool table is the point

GROWLER = HERE / "growler.gxwf.yml"
OUT = HERE / "growler_ucsc_pair.gxwf.yml"
BANNER = "# GENERATED by assemble_ucsc.py -- DO NOT EDIT BY HAND. Edit assemble_ucsc.py and rerun.\n"

UCSC_TOOLS = {
    **TOOLS,
    "lastz_lav": "gt-growler-lastz-lav",
    "lavtopsl": "gt-ucsc-lavtopsl",
    "axtsort": "gt-ucsc-axtsort",
    "chainantirepeat": f"{IUC}/ucsc_chainantirepeat/ucsc_chainantirepeat/482+galaxy0",
    "netsyntenic": f"{IUC}/ucsc_netsyntenic/ucsc_netsyntenic/482+galaxy0",
    "netfilter": f"{IUC}/ucsc_netfilter/ucsc_netfilter/482+galaxy0",
    "nettoaxt": f"{IUC}/ucsc_nettoaxt/ucsc_nettoaxt/482+galaxy0",
    "axttomaf": f"{IUC}/ucsc_axttomaf/ucsc_axtomaf/482+galaxy1",
}

#: Workflow inputs: (type, default, doc). Defaults are lastz's / doBlastzChainNet.pl's own.
PARAMS = {
    "hspthresh": ("integer", 3000, "blastz K. lastz default 3000."),
    "gappedthresh": ("integer", 3000, "blastz L; lastz default L=K. Fed to BOTH stages."),
    "xdrop": ("integer", 910, "blastz X. lastz's default is 10 x the matrix's A/A score."),
    "ydrop": ("integer", 9430, "blastz Y. lastz's default is O + 300E for the matrix used. Fed to BOTH stages."),
    "inner": ("integer", 0, "blastz H; 0 is off. UCSC hg38 x panTro6: 2000."),
    "masking": ("integer", 0, "blastz M; 0 is off. Acts in the gapped stage only (KegAlign seeds)."),
    "notransition": ("boolean", False, "blastz T=2 is 12of19 with --notransition."),
    "noentropy": ("boolean", False, "blastz P=1 (entropy on) is the default."),
    "chain_min_score": ("integer", 1000, "axtChain -minScore. doBlastzChainNet.pl's default is axtChain's own, 1000."),
    "batch_lines": ("integer", 1000000, "KegAlign segment lines per element; 0 is one element per chromosome pair."),
    "num_gpu": ("integer", 1, "KegAlign GPUs. The tool default, -1, means every GPU on the node."),
}
DATA = {
    "target_fasta": "Target genome, soft-masked FASTA.",
    "query_fasta": "Query genome, soft-masked FASTA.",
    "target_sizes": "Target chromosome sizes (name<TAB>length).",
    "query_sizes": "Query chromosome sizes.",
    "scores": "lastz scoring matrix, uploaded as tabular: KegAlign and lastz read it as text, axtChain as tabular.",
    "linear_gap": "axtChain gap-cost table: gap/loose.lineargap (chicken-human) or gap/medium.lineargap (mouse-human and closer).",
}
_NETS = {"minFill": None, "inclHap": False, "verbose": None}


def _net(chain: str, t: str, q: str, label: str, min_score) -> dict:
    """chainNet -minSpace=1 [-minScore=...] on target/query sizes t,q -- fresh dicts every call."""
    i, s = _sizes(t, q)
    return {"tool_id": UCSC_TOOLS["chainnet"], "label": label, "in": {"in_chain": chain, **i},
            "state": {**s, "minSpace": 1, "minScore": min_score, **_NETS}}


def _prenet(chain: str, t: str, q: str, label: str) -> dict:
    i, s = _sizes(t, q)
    return {"tool_id": UCSC_TOOLS["chainprenet"], "label": label, "in": {"in_chain": chain, **i},
            "state": {**s, "pad": None, "inclHap": False}}


def _step(tool: str, label: str, inputs: dict, state: dict | None = None) -> dict:
    d = {"tool_id": UCSC_TOOLS[tool], "label": label, "in": inputs}
    if state is not None:
        d["state"] = state
    return d


def _to_maf(prefix: str, net: str, chain: str) -> dict:
    """netToAxt | axtSort | axtToMaf, as doBlastzChainNet.pl builds every MAF it ships."""
    _i, s = _sizes("target_sizes", "query_sizes")
    return {
        f"{prefix}_axt": _step("nettoaxt", f"{prefix}_axt", {"in_net": net, "in_chain": chain,
                               "in_target": "kegalign/target_2bit", "in_query": "kegalign/query_2bit"},
                               {"qChain": False, "maxGap": None, "noSplit": False}),
        f"{prefix}_sorted": _step("axtsort", f"{prefix}_sorted", {"input": f"{prefix}_axt/out"}),
        f"{prefix}_maf": _step("axttomaf", f"{prefix}_maf",
                               {"in_axt": f"{prefix}_sorted/output",
                                "target_reference_index_source|in_tar_ref_index": "target_sizes",
                                "query_reference_index_source|in_que_ref_index": "query_sizes"},
                               {**s, "t_prefix": None, "q_prefix": None, "score": False, "scoreZero": False}),
    }


def build(growler: dict) -> dict:
    kegalign = copy.deepcopy(growler["steps"]["kegalign"])
    kegalign.pop("position", None)
    kegalign["in"] = {
        "target": "target_fasta", "query": "query_fasta", "scoring_options|scoring": "scores",
        "seeding_options|notransition": "notransition",
        "ungapped_extension_options|hspthresh": "hspthresh",
        "ungapped_extension_options|xdrop": "xdrop",
        "ungapped_extension_options|noentropy": "noentropy",
        "gapped_extension_options|gappedthresh": "gappedthresh",
        "gapped_extension_options|ydrop": "ydrop",
        "batch_lines": "batch_lines", "system_options|num_gpu": "num_gpu"}
    st = kegalign["state"]
    st.pop("batch_lines", None)
    st["gapped_extension_options"] = {"notrivial": False}
    st["system_options"]["debug"] = True
    st["seeding_options"]["step"] = 1

    steps = {"kegalign": kegalign}
    steps["lastz_lav"] = _step("lastz_lav", "lastz_lav", {
        "pair": "kegalign/pairs", "target": "kegalign/target_2bit", "query": "kegalign/query_2bit",
        "scores": "scores", "gappedthresh": "gappedthresh", "ydrop": "ydrop", "inner": "inner",
        "masking": "masking"})
    steps["lavtopsl"] = _step("lavtopsl", "lavtopsl", {"input": "lastz_lav/output"})
    steps["axtchain"] = _step("axtchain", "axtchain", {
        "in_aln": "lavtopsl/output", "in_target": "kegalign/target_2bit",
        "in_query": "kegalign/query_2bit", "scoreScheme": "scores", "minScore": "chain_min_score",
        "linear_gap_options|lineargap_input": "linear_gap"},
        {"linear_gap_options": {"linear_gap": "linear_gap_file"}, "details_output": False})
    steps["chainantirepeat"] = _step("chainantirepeat", "chainantirepeat", {
        "in_chain": "axtchain/out", "in_target": "kegalign/target_2bit",
        "in_query": "kegalign/query_2bit"}, {"minScore": None, "noCheckScore": None})
    steps["chainmergesort"] = _step("chainmergesort", "chainmergesort",
                                    {"in_chains": "chainantirepeat/out"})
    # --- the net, the liftOver chain (doBlastzChainNet.pl 1012-1018)
    steps["prenet"] = _prenet("chainmergesort/out", "target_sizes", "query_sizes", "prenet")
    steps["net"] = _net("prenet/out", "target_sizes", "query_sizes", "net", None)
    steps["netsyntenic"] = _step("netsyntenic", "netsyntenic", {"in_net": "net/targetNet"})
    steps["over_subset"] = _step("netchainsubset", "over_subset",
                                 {"in_net": "netsyntenic/out", "in_chain": "chainmergesort/out"},
                                 {"splitOnInsert": False, "wholeChains": False, "skipMissing": False})
    steps["over_chain"] = _step("chainstitchid", "over_chain", {"input": "over_subset/out"})
    # --- synNet and its MAF (1861-1870)
    steps["syn_net"] = _step("netfilter", "syn_net", {"in_net": "netsyntenic/out"},
                             {"synteny": {"syn_filter": "filtersyn", "syntype": "-syn",
                                          "minSynScore": None, "minSynSize": None, "minSynAli": None},
                              "minGap": None})
    # ⛔ THE SYNNET MAF READS over.chain, NOT all.chain -- the one deliberate departure from
    # doBlastzChainNet.pl (line 1867), which hands netToAxt the full chain file. netToAxt loads every
    # chain it is given; all.chain is 7.6 GB for cs10 x 79X, and the job was OOM-killed on vgp (and at
    # a 12 GB cap locally). over.chain is netChainSubset(noClass.net, all.chain) | chainStitchId, and a
    # synNet's fills are a subset of the net's, so it holds every chain part netToAxt can look up.
    # Measured byte-identical AXT: hg38 x panTro6 chr21 (1,727 blocks) and cs10 x EH23a.chr1 (31,346
    # blocks, peak 2.6 -> 0.48 GB); cs10 x 79X now runs in 1.6 GB from a 42 MB chain file.
    steps.update(_to_maf("synnet", "syn_net/out", "over_chain/output"))
    # --- doRecipBest.pl 144-171
    steps["rb_stitch1"] = _step("chainstitchid", "rb_stitch1", {"input": "over_chain/output"})
    steps["rb_swap1"] = _step("chainswap", "rb_swap1", {"in_chain": "rb_stitch1/output"})
    steps["rb_sort1"] = _step("chainsort", "rb_sort1", {"in_chain": "rb_swap1/out"}, {"sort_by": ""})
    steps["rb_prenet_q"] = _prenet("rb_sort1/out", "query_sizes", "target_sizes", "rb_prenet_q")
    steps["rb_net_q"] = _net("rb_prenet_q/out", "query_sizes", "target_sizes", "rb_net_q", 0)
    steps["rb_syn_q"] = _step("netsyntenic", "rb_syn_q", {"in_net": "rb_net_q/targetNet"})
    steps["rb_subset"] = _step("netchainsubset", "rb_subset",
                               {"in_net": "rb_syn_q/out", "in_chain": "rb_sort1/out"},
                               {"splitOnInsert": False, "wholeChains": False, "skipMissing": False})
    steps["rb_stitch2"] = _step("chainstitchid", "rb_stitch2", {"input": "rb_subset/out"})
    steps["rb_swap2"] = _step("chainswap", "rb_swap2", {"in_chain": "rb_stitch2/output"})
    steps["rb_chain"] = _step("chainsort", "rb_chain", {"in_chain": "rb_swap2/out"}, {"sort_by": ""})
    steps["rb_prenet_t"] = _prenet("rb_chain/out", "target_sizes", "query_sizes", "rb_prenet_t")
    steps["rb_net_t"] = _net("rb_prenet_t/out", "target_sizes", "query_sizes", "rb_net_t", 0)
    steps["rb_net"] = _step("netsyntenic", "rb_net", {"in_net": "rb_net_t/targetNet"})
    steps.update(_to_maf("rbest", "rb_net/out", "rb_chain/out"))

    inputs = {k: {"type": "data", "doc": v} for k, v in DATA.items()}
    inputs.update({k: {"type": t, "default": d, "doc": doc} for k, (t, d, doc) in PARAMS.items()})
    outputs = {
        "all_chain": {"outputSource": "chainmergesort/out", "doc": "hg38.panTro6.all.chain analogue"},
        "net": {"outputSource": "netsyntenic/out", "doc": "noClass.net"},
        "over_chain": {"outputSource": "over_chain/output", "doc": "the liftOver chain"},
        "syn_net": {"outputSource": "syn_net/out"},
        "synnet_maf": {"outputSource": "synnet_maf/out", "doc": "multiz input for close genomes"},
        "rbest_chain": {"outputSource": "rb_chain/out"},
        "rbest_net": {"outputSource": "rb_net/out"},
        "rbest_maf": {"outputSource": "rbest_maf/out", "doc": "multiz input for other genomes"},
        "lav": {"outputSource": "lastz_lav/output", "doc": "per-element LAV, kept: the raw alignment record"},
    }
    return {"class": "GalaxyWorkflow", "label": "Growler UCSC pair (KegAlign + UCSC chain/net, flat)",
            "doc": "One genome pair: KegAlign seeding, then kent's doBlastzChainNet.pl and doRecipBest.pl "
                   "steps. See assemble_ucsc.py for the line-by-line provenance.",
            "inputs": inputs, "outputs": outputs, "steps": steps}


CHAIN_OUT = HERE / "growler_ucsc_chain.gxwf.yml"
#: The chain-only document keeps these of PARAMS; the rest drive seeding and lastz, which it skips.
CHAIN_PARAMS = ("chain_min_score",)


def build_chain_only(full: dict) -> dict:
    """growler_ucsc_pair from axtChain onward, reading a COLLECTION of existing alignments.

    ▶ For parameter sweeps and for alignments computed elsewhere. Derived from `full`, never written:
    the seeding and lastz steps are removed and their outputs rewired to inputs, so every chain/net
    step is the pair document's own, and `assert_chain_arm_identical` proves it.
    axtChain takes AXT or PSL, so the collection may be either.
    """
    doc = copy.deepcopy(full)
    doc["label"] = "Growler UCSC chain/net (from existing alignments, flat)"
    for k in ("kegalign", "lastz_lav", "lavtopsl"):
        del doc["steps"][k]
    rewire = {"kegalign/target_2bit": "target_2bit", "kegalign/query_2bit": "query_2bit",
              "lavtopsl/output": "alignments"}
    for st in doc["steps"].values():
        st["in"] = {k: rewire.get(v, v) for k, v in st["in"].items()}
    keep = {k: v for k, v in doc["inputs"].items() if k in DATA and k not in ("target_fasta", "query_fasta")}
    keep.update({k: doc["inputs"][k] for k in CHAIN_PARAMS})
    doc["inputs"] = {"alignments": {"type": "collection", "collection_type": "list",
                                    "doc": "AXT or PSL, one element per piece (e.g. growler_lastz output)."},
                     "target_2bit": {"type": "data"}, "query_2bit": {"type": "data"}, **keep}
    del doc["outputs"]["lav"]
    return doc


def assert_chain_arm_identical(full: dict, chain: dict) -> list[str]:
    """Every step the chain-only document has must equal the pair document's, up to the rewiring."""
    rewire = {"kegalign/target_2bit": "target_2bit", "kegalign/query_2bit": "query_2bit",
              "lavtopsl/output": "alignments"}
    bad = []
    for name, st in chain["steps"].items():
        ref = copy.deepcopy(full["steps"][name])
        ref["in"] = {k: rewire.get(v, v) for k, v in ref["in"].items()}
        if ref != st:
            bad.append(name)
    missing = set(full["steps"]) - set(chain["steps"]) - {"kegalign", "lastz_lav", "lavtopsl"}
    return bad + [f"missing {m}" for m in sorted(missing)]


#: (step, input, must read from) -- the wiring that makes this UCSC's pipeline and not a lookalike.
UCSC_ORDER = [
    ("lavtopsl", "input", "lastz_lav/output"),
    ("axtchain", "in_aln", "lavtopsl/output"),
    ("chainantirepeat", "in_chain", "axtchain/out"),
    ("chainmergesort", "in_chains", "chainantirepeat/out"),
    ("prenet", "in_chain", "chainmergesort/out"),
    ("net", "in_chain", "prenet/out"),
    ("netsyntenic", "in_net", "net/targetNet"),
    ("over_subset", "in_net", "netsyntenic/out"),
    ("over_subset", "in_chain", "chainmergesort/out"),   # all.chain, NOT the pre-netted chain
    ("syn_net", "in_net", "netsyntenic/out"),
    ("synnet_axt", "in_chain", "over_chain/output"),   # see build(): identical output, bounded memory
    ("rb_stitch1", "input", "over_chain/output"),
    ("rb_net_q", "in_chain", "rb_prenet_q/out"),
    ("rb_subset", "in_chain", "rb_sort1/out"),
    ("rb_prenet_t", "in_chain", "rb_chain/out"),
    ("rbest_axt", "in_net", "rb_net/out"),
    ("rbest_axt", "in_chain", "rb_chain/out"),
]


def assert_ucsc_order(doc: dict) -> list[str]:
    return [f"{s}.{i} reads {doc['steps'].get(s, {}).get('in', {}).get(i)!r}, expected {want!r}"
            for s, i, want in UCSC_ORDER if doc["steps"].get(s, {}).get("in", {}).get(i) != want]


def dangling(doc: dict) -> list[str]:
    known = set(doc["inputs"]) | set(doc["steps"])
    out = [f"{n}.{k} <- {v}" for n, s in doc["steps"].items() for k, v in s["in"].items()
           if v is None or v.split("/")[0] not in known]
    out += [f"output {k}" for k, v in doc["outputs"].items() if v["outputSource"].split("/")[0] not in known]
    return out


def self_test() -> int:
    doc = build(yaml.safe_load(GROWLER.read_text(encoding="utf-8")))
    fails = 0

    def check(name: str, cond: bool) -> None:
        nonlocal fails
        fails += not cond
        print(f"  {'ok ' if cond else 'FAIL'} {name}")

    check("no dangling connection", dangling(doc) == [])
    check("wired in UCSC's order", assert_ucsc_order(doc) == [])
    check("no nested subworkflow", not any("run" in s for s in doc["steps"].values()))
    nets = {k: doc["steps"][k]["state"] for k in ("net", "rb_net_q", "rb_net_t")}
    check("both reciprocal-best nets use -minSpace=1 -minScore=0",
          all(nets[k]["minSpace"] == 1 and nets[k]["minScore"] == 0 for k in ("rb_net_q", "rb_net_t")))
    check("the main net uses -minSpace=1 and no minScore",
          nets["net"]["minSpace"] == 1 and nets["net"]["minScore"] is None)
    keg, lz, ax = doc["steps"]["kegalign"]["in"], doc["steps"]["lastz_lav"]["in"], doc["steps"]["axtchain"]
    check("gappedthresh and ydrop reach BOTH stages",
          keg.get("gapped_extension_options|gappedthresh") == "gappedthresh"
          and keg.get("gapped_extension_options|ydrop") == "ydrop"
          and lz["gappedthresh"] == "gappedthresh" and lz["ydrop"] == "ydrop")
    check("axtChain reads PSL, the scoring matrix, and the gap file",
          ax["in"]["in_aln"] == "lavtopsl/output" and ax["in"]["scoreScheme"] == "scores"
          and ax["state"]["linear_gap_options"]["linear_gap"] == "linear_gap_file")
    bad = copy.deepcopy(doc)
    bad["steps"]["over_subset"]["in"]["in_chain"] = "prenet/out"
    check("  and netChainSubset on the PRE-NETTED chain is caught", assert_ucsc_order(bad) != [])
    for g in ("loose", "medium"):
        check(f"gap/{g}.lineargap is present", (HERE / "gap" / f"{g}.lineargap").exists())
    chain = build_chain_only(doc)
    check("chain-only: no dangling connection", dangling(chain) == [])
    check("chain-only: every step identical to the pair document's", assert_chain_arm_identical(doc, chain) == [])
    check("chain-only: axtChain reads the alignments collection", chain["steps"]["axtchain"]["in"]["in_aln"] == "alignments")
    tampered = copy.deepcopy(chain)
    tampered["steps"]["net"]["state"]["minSpace"] = 25
    check("  and a drifted chain step is caught", assert_chain_arm_identical(doc, tampered) == ["net"])
    if OUT.exists():
        committed = yaml.safe_load(OUT.read_text(encoding="utf-8"))
        check("the committed document matches a fresh build", committed == doc)
    if CHAIN_OUT.exists():
        check("the committed chain-only document matches", yaml.safe_load(CHAIN_OUT.read_text(encoding="utf-8")) == chain)
    print("\nall tests passed" if not fails else f"\n{fails} FAILED")
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    doc = build(yaml.safe_load(GROWLER.read_text(encoding="utf-8")))
    problems = dangling(doc) + assert_ucsc_order(doc)
    if problems:
        sys.exit("REFUSING:\n  " + "\n  ".join(problems))
    chain = build_chain_only(doc)
    problems = assert_chain_arm_identical(doc, chain) + dangling(chain)
    if problems:
        sys.exit("REFUSING the chain-only document:\n  " + "\n  ".join(problems))
    for path, d in ((OUT, doc), (CHAIN_OUT, chain)):
        if a.check:
            if not path.exists() or yaml.safe_load(path.read_text(encoding="utf-8")) != d:
                sys.exit(f"{path.name} is stale -- run assemble_ucsc.py and commit")
            print(f"{path.name} is current")
            continue
        path.write_text(BANNER + yaml.safe_dump(d, sort_keys=False, allow_unicode=True, width=100),
                        encoding="utf-8")
        print(f"wrote {path.name} ({len(d['steps'])} steps)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
