#!/usr/bin/env python3
"""Assemble the workflows that inline Growler as a subworkflow.

    ./assemble.py                 # writes growler_pair.gxwf.yml and growler_panel.gxwf.yml
    ./assemble.py --check         # non-zero if either committed file is stale
    ./assemble.py --self-test

TWO DOCUMENTS ARE GENERATED FROM ONE, and they are different shapes on purpose:

  growler_pair.gxwf.yml   ONE genome pair in, `cleaned_chains` / `rbest_chains` / `pairwise_axt`
                          out. The per-pair WRAPPER: it creates the chromosome-pair axis inside
                          itself and collapses it again before returning, so its caller never
                          sees a list:list. This is what WF-C maps over.
  growler_panel.gxwf.yml  every ordered genome pair, Growler alone, alignments out. The
                          standalone demonstration; it has no chain steps.

⛔ THERE IS ONE SOURCE OF TRUTH AND IT IS `growler.gxwf.yml`. gxformat2 has no include: a
subworkflow step carries the whole child document inline under `run:`. Writing the panel workflow
by hand would mean a second copy of Growler that drifts from the first, which is the defect this
project already has four instances of (two scripts, four copies, in two repositories). So the
panel file is GENERATED, and `--check` fails the build if it stops matching.

▶ WHY THE PANEL CASE IS A SUBWORKFLOW AT ALL, rather than the same steps flattened:

Galaxy does not broadcast a dataset across nesting levels. Flattened, `growler_lastz` would have to
be mapped over the INNER (chromosome-pair) level while its 2bits sit at the OUTER (genome-pair)
level, and there is no native operation that expands one dataset across N identifiers -- brc-tools
works around this by materialising parallel `list:list` collections with matching identifiers.

Inside a Growler invocation there is only one level: one genome pair, two 2bits as plain `data`
inputs, a flat collection of pair files. The nesting problem does not get solved here, it stops existing.
And the outer `list:list` is produced for free: a subworkflow mapped over a list, emitting a
collection, yields `list:list` with outer identifiers preserved -- measured on usegalaxy.org 26.1
on 2026-09-17, in exactly this shape.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import zlib

import yaml

HERE = pathlib.Path(__file__).resolve().parent
GROWLER = HERE / "growler.gxwf.yml"
PANEL = HERE / "growler_panel.gxwf.yml"
PAIR = HERE / "growler_pair.gxwf.yml"

BANNER = """# GENERATED by assemble.py from growler.gxwf.yml -- DO NOT EDIT BY HAND.
# gxformat2 has no include directive, so the subworkflow is inlined. Edit growler.gxwf.yml and
# re-run ./assemble.py; ./assemble.py --check fails if this file is stale.
"""


def build(growler: dict) -> dict:
    """The panel workflow: every ordered genome pair, self-pairs dropped, Growler mapped over."""
    return {
        "class": "GalaxyWorkflow",
        "label": "Growler panel (every genome pair)",
        "doc": (
            "Runs Growler over every ordered pair of a genome collection.\n\n"
            "__CROSS_PRODUCT_FLAT__ emits two aligned flat lists; feeding output_a to the target\n"
            "input and output_b to the query input is how a pair reaches a two-input consumer\n"
            "natively -- Galaxy then matches them element-wise. __FILTER_FROM_FILE__ removes the\n"
            "diagonal, which is the N self-pairs an all-against-all grid always contains and which\n"
            "are meaningless to align.\n\n"
            "The output is list:list -- outer = genome pair, inner = chromosome pair -- with both\n"
            "identifiers preserved, so downstream steps can regroup on either axis.\n\n"
            "⚠ Job count is the scaling wall, not compute. For a panel of N genomes with C\n"
            "chromosomes this is N*(N-1) Growler invocations, each mapping LASTZ over roughly C^2\n"
            "pair files. Ten genomes of ten chromosomes is ~9,000 LASTZ jobs; fourteen chromosomes across\n"
            "ten genomes is ~17,600. That is Galaxy's scheduler and database, not the aligner."
        ),
        "inputs": {
            "genomes": {
                "type": "collection",
                "collection_type": "list",
                "doc": "Soft-masked genomes, one element per strain. These element identifiers "
                       "become the pair ids and, eventually, browser track names.",
                "position": {"top": 0, "left": 0},
            },
            "self_pairs": {
                "type": "data",
                "doc": "One 'X_X' line per strain. A file rather than a parameter because Galaxy "
                       "filters collections by matching identifiers against file CONTENT, and the "
                       "identifiers are only known once the panel is chosen.",
                "position": {"top": 150, "left": 0},
            },
            "scores": {
                "type": "data",
                "optional": True,
                "doc": "Scoring file in LASTZ format, shared by every pair.",
                "position": {"top": 260, "left": 0},
            },
            "output_format": {
                "type": "text",
                "default": "axt",
                "doc": "LASTZ output format, shared by every pair. Defaults to axt because the "
                       "consumer is axtChain, which accepts axt,psl only. Lifted to the panel "
                       "rather than left at the subworkflow's default so that ONE setting governs "
                       "the whole panel -- a panel whose pairs disagreed about their format would "
                       "produce a collection its consumer can only partly read.",
                "position": {"top": 370, "left": 0},
            },
        },
        "steps": {
            "pairs": {
                "tool_id": "__CROSS_PRODUCT_FLAT__",
                "label": "pairs",
                "in": {"input_a": "genomes", "input_b": "genomes"},
                "position": {"top": 0, "left": 260},
            },
            "targets": {
                "tool_id": "__FILTER_FROM_FILE__",
                "label": "targets",
                "in": {"input": "pairs/output_a", "how|filter_source": "self_pairs"},
                "state": {"how": {"how_filter": "remove_if_present"}},
                "position": {"top": 0, "left": 520},
            },
            "queries": {
                "tool_id": "__FILTER_FROM_FILE__",
                "label": "queries",
                "in": {"input": "pairs/output_b", "how|filter_source": "self_pairs"},
                "state": {"how": {"how_filter": "remove_if_present"}},
                "position": {"top": 160, "left": 520},
            },
            "growler": {
                "run": growler,
                "label": "growler",
                "doc": "Mapped over the pair lists. Each invocation sees one genome pair and "
                       "emits a flat pair file collection; Galaxy nests those into list:list.",
                "in": {"target_fasta": "targets/output_filtered",
                       "query_fasta": "queries/output_filtered",
                       "scores": "scores",
                       "output_format": "output_format"},
                "position": {"top": 0, "left": 800},
            },
        },
        "outputs": {
            "alignments": {"outputSource": "growler/alignments"},
        },
    }


# --------------------------------------------------------------------------------- the wrapper

#: The tool ids the chain arm is lifted from, verbatim out of WF-C's align_chain.gxwf.yml. Kept as
#: one table so a drift between the wrapper and WF-C is a one-line diff rather than a hunt.
#:
#: ⛔ THE STITCH STEP IS A USER-DEFINED TOOL, AND IT HAS TO BE. `chainStitchId` is the one chain
#: utility the IUC collection does not carry. brc-tools holds it twice: a shed wrapper at
#: `tools/chainStitchId/` that has NEVER BEEN PUBLISHED (the Tool Shed returns no results for it),
#: and a UDT generated from that wrapper. WF-C therefore has two editions, and the bare
#: `chainStitchId` in its classic one resolves only where a local tool_conf.xml provides it.
#:
#: This document lifted the classic id and so named a tool that resolves on NEITHER usegalaxy.org
#: NOR vgp -- measured, `/api/tools/chainStitchId` is 404 on both. `brc-chain-stitch-id` is live
#: and active on both, so that is what this uses. ▶ This wrapper corresponds to WF-C's UDT
#: edition, not its classic one; there is no variant of it that runs on a public server without
#: the UDT, so no second edition is generated here.
#:
#: ⚠ FIVE registrations of `brc-chain-stitch-id` are active, created within twelve minutes of each
#: other on 2026-09-01 -- a UDT cannot be updated in place, so each re-registration adds one. They
#: are identical (version 0.1.0, inputs ['input'], outputs ['output']), so resolving by name is
#: unambiguous in effect. If they ever diverge, that stops being true silently.
#:
#: ⚠ `ucsc_chainmergesort` is bare for a different reason: it is written in this same repository
#: (tools/ucsc_chainmergesort) and has no published revision to pin. PIN IT once it is on the
#: target server, or this document silently accepts any future version of the step the whole
#: collapse turns on.
IUC = "toolshed.g2.bx.psu.edu/repos/iuc"
TOOLS = {
    "axtchain": f"{IUC}/ucsc_axtchain/ucsc_axtchain/482+galaxy2",
    "chainmergesort": "ucsc_chainmergesort",
    "chainprenet": f"{IUC}/ucsc_chainprenet/ucsc_chainprenet/482+galaxy0",
    "chainnet": f"{IUC}/ucsc_chainnet/ucsc_chainnet/482+galaxy0",
    "netchainsubset": f"{IUC}/ucsc_netchainsubset/ucsc_netchainsubset/482+galaxy0",
    "chainstitchid": "brc-chain-stitch-id",
    "chainswap": f"{IUC}/ucsc_chainswap/ucsc_chainswap/482+galaxy0",
    "chainsort": f"{IUC}/ucsc_chainsort/ucsc_chainsort/482+galaxy0",
    # ⚠ The AXT branch needs a collapse too, and it is NOT the chain one. A chain merge must be a
    # score-ordered k-way merge; AXT blocks are independent records, so concatenation is the whole
    # operation. This tool takes a collection into a multiple="true" data input -- one job -- and
    # its output carries `format_source="input"`, so the axt datatype rides through.
    "cat_multiple": "toolshed.g2.bx.psu.edu/repos/mvdbeek/concatenate_multiple_datasets/cat_multiple/0.2",
}


#: chainNet and chainPreNet take the two .sizes files the same way in every step that uses them.
#: Written once because getting the target/query pair the wrong way round is silent: the run
#: succeeds and the net is computed against the wrong coordinate space.
def _sizes(target: str, query: str) -> tuple[dict, dict]:
    return (
        {
            "target_reference_index_source|in_tar_ref_index": target,
            "query_reference_index_source|in_que_ref_index": query,
        },
        {
            "target_reference_index_source": {"target_reference_index_source_selector": "history"},
            "query_reference_index_source": {"query_reference_index_source_selector": "history"},
        },
    )


def build_pair(growler: dict) -> dict:
    """The per-genome-pair WRAPPER: Growler, then WF-C's chain arm, for ONE pair.

    ▶ WHAT THIS BUYS, AND IT IS THE WHOLE REASON FOR THE SHAPE. The chromosome-pair axis is created
    AND collapsed inside this document, so WF-C never sees a `list:list` and stays what it is
    today: a flat map over the genome-pair grid with one step swapped, inputs and outputs unchanged.

    ⛔ THE COLLAPSE IS AT `chainMergeSort` AND CANNOT MOVE LATER. `chainPreNet` and `chainNet` each
    walk ONE score-ordered stream marking target and query space simultaneously, so a chain on
    (tchr1, qchr5) consumes query space a chain on (tchr3, qchr5) would otherwise claim. No
    chromosome partition of either tool is correct. A per-TARGET partition is measurably safe on
    the main arm -- byte-identical `cleaned_chains` over four fixtures -- and breaks on the
    reciprocal-best arm, where after `rb_swap1` the target axis IS the query axis: `rbest_chains`
    came out +48% (191 chains / 300,773 bp against 143 / 203,579). And it fails QUIETLY: a
    partition of a sorted file is still sorted, so the errAbort cannot fire.

    ⛔ `chainMergeSort` REPLACES WF-C's `chainsort_clean` rather than adding a pass -- it emits
    score-sorted output, which is exactly `chainPreNet`'s precondition. Step count unchanged, and
    parallel `axtChain` gained.

    ⛔ AND NEVER `-saveId`. Independent `axtChain` runs each number their chains from 1, so the
    mapped jobs arrive with colliding ids and `netChainSubset` matches nets to chains BY ID.
    `chainMergeSort` renumbers by default, which repairs exactly this; the wrapper in
    tools/ucsc_chainmergesort does not expose the flag, for this reason.
    """
    sizes_in, sizes_state = _sizes("target_sizes", "query_sizes")
    # the reciprocal-best net runs in the SWAPPED frame, so its two sizes files are the other way
    rb_sizes_in, rb_sizes_state = _sizes("query_sizes", "target_sizes")
    return {
        "class": "GalaxyWorkflow",
        "label": "Growler pair (one genome pair, through chains)",
        "doc": (
            "One genome pair in; cleaned chains, reciprocal-best chains and the pairwise AXT out.\n\n"
            "Growler is nested inside, so the chromosome-pair axis is born at growler_lastz and "
            "dies at chainMergeSort, both inside this document. The caller therefore maps over a "
            "flat genome-pair list and gets flat outputs back -- it never handles list:list.\n\n"
            "⚠ axtChain is MAPPED over the chromosome-pair axis and takes the whole target and "
            "query genome in every one of those jobs. Measured on a real Cannabis chromosome pair "
            "over three alignment sizes spanning 240x, whole-genome FASTA costs a FIXED "
            "+1.30 to +1.36 GB of peak RSS against the same run given 2bit, with byte-identical "
            "chain counts. On a realistic job -- 1.69 GB of AXT, 1.7 million chains -- that is "
            "3.58 GB against 2.23 GB, so it is the memory a TPV entry must carry rather than a "
            "runtime problem: the same fixed cost is only +6.4 s on a 128 s job, about 5%.\n\n"
            "▶ It is recoverable for nothing. KegAlign already emits both 2bits and Growler "
            "already carries them; ucsc_axtchain hardcodes -faT/-faQ and declares its sequence "
            "inputs as fasta, so this document passes FASTA as WF-C does until that changes.\n\n"
            "⚠ The chain arm is lifted verbatim from WF-C, including its DELIBERATE divergence "
            "from doRecipBest.pl: chainNet alone on its defaults, no chainPreNet on the rbest arm."
        ),
        "inputs": {
            "target_fasta": {"type": "data", "doc": "Soft-masked target genome.",
                             "position": {"top": 0, "left": 0}},
            "query_fasta": {"type": "data", "doc": "Soft-masked query genome.",
                            "position": {"top": 110, "left": 0}},
            "target_sizes": {"type": "data", "doc": "Target .sizes, for chainPreNet and chainNet.",
                             "position": {"top": 220, "left": 0}},
            "query_sizes": {"type": "data", "doc": "Query .sizes.",
                            "position": {"top": 330, "left": 0}},
            "scores": {"type": "data", "optional": True,
                       "doc": "Scoring file in LASTZ format, wired to both alignment stages.",
                       "position": {"top": 440, "left": 0}},
            "output_format": {
                "type": "text",
                "default": "axt",
                "doc": "LASTZ output format. ⛔ The chain arm REQUIRES axt -- axtChain accepts "
                       "axt,psl only. It is an input rather than a constant so that one setting "
                       "governs Growler and this document together, and it is asserted in the "
                       "generator's self-test because a wrong value fails at the axtChain job "
                       "rather than at edit time.",
                "position": {"top": 550, "left": 0},
            },
        },
        "steps": {
            "growler": {
                "run": growler,
                "label": "growler",
                "doc": "KegAlign on the GPU, then LASTZ mapped over the pair files. The inner axis "
                       "is born here: one alignment per chromosome pair, keyed <target>__<query>.",
                "in": {"target_fasta": "target_fasta", "query_fasta": "query_fasta",
                       "scores": "scores", "output_format": "output_format"},
                "position": {"top": 0, "left": 300},
            },
            "axtchain": {
                "tool_id": TOOLS["axtchain"],
                "label": "axtchain",
                "doc": "MAPPED over the chromosome-pair axis. The two genomes are plain data "
                       "inputs, which Galaxy broadcasts across the map -- that is allowed; it is "
                       "broadcasting across NESTING LEVELS that is not, which is why Growler is "
                       "nested rather than flattened.",
                "in": {"in_aln": "growler/alignments", "in_target": "target_fasta",
                       "in_query": "query_fasta"},
                "state": {"linear_gap_options": {"linear_gap": "loose"}},
                "position": {"top": 0, "left": 600},
            },
            "chainmergesort": {
                "tool_id": TOOLS["chainmergesort"],
                "label": "chainmergesort",
                "doc": "⛔ THE COLLAPSE. The chromosome-pair collection meets a multiple=\"true\" "
                       "data input, so Galaxy consumes every element in ONE job rather than "
                       "mapping over them. VERIFIED IN GALAXY'S SOURCE, not assumed: "
                       "lib/galaxy/workflow/modules.py gives a multiple data param an effective "
                       "collection type of `list` (\"acts like 'list' collection_type\") and only a "
                       "SINGLE-valued data param reaches collections_to_match, which is what "
                       "causes mapping. ⚠ The corollary matters if anyone ever flattens this "
                       "workflow: handed a list:list, the same step would map over the OUTER "
                       "level and consume the inner one. It also renumbers the chain ids, which "
                       "is what repairs the collisions the independent axtChain jobs necessarily "
                       "produce.",
                "in": {"in_chains": "axtchain/out"},
                "position": {"top": 0, "left": 900},
            },
            "chainprenet": {
                "tool_id": TOOLS["chainprenet"],
                "label": "chainprenet",
                "in": {"in_chain": "chainmergesort/out", **sizes_in},
                "state": sizes_state,
                "position": {"top": 0, "left": 1200},
            },
            "chainnet": {
                "tool_id": TOOLS["chainnet"],
                "label": "chainnet",
                "in": {"in_chain": "chainprenet/out", **sizes_in},
                "state": sizes_state,
                "position": {"top": 0, "left": 1500},
            },
            "netchainsubset": {
                "tool_id": TOOLS["netchainsubset"],
                "label": "netchainsubset",
                "in": {"in_net": "chainnet/targetNet", "in_chain": "chainprenet/out"},
                "position": {"top": 0, "left": 1800},
            },
            "chainstitchid_clean": {
                "tool_id": TOOLS["chainstitchid"],
                "label": "chainstitchid_clean",
                "doc": "Both the cleaned_chains deliverable AND the reciprocal-best arm's input.",
                "in": {"input": "netchainsubset/out"},
                "position": {"top": 0, "left": 2100},
            },
            "rb_swap1": {
                "tool_id": TOOLS["chainswap"],
                "label": "rb_swap1",
                "doc": "⛔ AFTER THIS SWAP THE TARGET AXIS IS THE QUERY AXIS, which is why no "
                       "chromosome partition of the arm below is safe, and why the collapse "
                       "cannot be moved down past chainMergeSort.",
                "in": {"in_chain": "chainstitchid_clean/output"},
                "position": {"top": 200, "left": 2400},
            },
            "rb_sort1": {
                "tool_id": TOOLS["chainsort"],
                "label": "rb_sort1",
                "in": {"in_chain": "rb_swap1/out"},
                "position": {"top": 200, "left": 2700},
            },
            "rb_net": {
                "tool_id": TOOLS["chainnet"],
                "label": "rb_net",
                "doc": "⚠ DELIBERATELY NOT doRecipBest.pl. That recipe is chainPreNet | chainNet "
                       "-minSpace=1 -minScore=0 | netSyntenic; this is chainNet alone on its "
                       "defaults. Measured on a 10 Mb Cannabis slice, UCSC's flags add 9x the "
                       "chain records for 2.56% more aligned sequence, 93.7% of it in fragments "
                       "under 100 bp. ⚠ That slice was chosen to be homologous and its decisive "
                       "bin is n=44: re-measure before applying this to a divergent panel.",
                "in": {"in_chain": "rb_sort1/out", **rb_sizes_in},
                "state": rb_sizes_state,
                "position": {"top": 200, "left": 3000},
            },
            "rb_subset": {
                "tool_id": TOOLS["netchainsubset"],
                "label": "rb_subset",
                "in": {"in_net": "rb_net/targetNet", "in_chain": "rb_sort1/out"},
                "position": {"top": 200, "left": 3300},
            },
            "rb_stitch": {
                "tool_id": TOOLS["chainstitchid"],
                "label": "rb_stitch",
                "in": {"input": "rb_subset/out"},
                "position": {"top": 200, "left": 3600},
            },
            "rb_swap2": {
                "tool_id": TOOLS["chainswap"],
                "label": "rb_swap2",
                "doc": "⛔ SWAPS BACK. Without this pair of steps rbest_chains comes out "
                       "QUERY-referenced, which every downstream consumer reads as target-"
                       "referenced and nothing raises.",
                "in": {"in_chain": "rb_stitch/output"},
                "position": {"top": 200, "left": 3900},
            },
            "rb_sort2": {
                "tool_id": TOOLS["chainsort"],
                "label": "rb_sort2",
                "in": {"in_chain": "rb_swap2/out"},
                "position": {"top": 200, "left": 4200},
            },
            "axt_concat": {
                "tool_id": TOOLS["cat_multiple"],
                "label": "axt_concat",
                "doc": "⛔ THE SECOND COLLAPSE, AND THE PLAN'S OWN DIAGRAM LEFT IT OUT. That "
                       "diagram runs `growler_lastz output -> pairwise_axt` directly, which "
                       "hands the caller a COLLECTION where WF-C declares a dataset -- so WF-C "
                       "would see list:list on this one output, which is the exact property the "
                       "wrapper exists to prevent. Concatenation is the whole operation here "
                       "because AXT blocks are independent records; only the chain branch needs "
                       "a score-ordered merge.",
                "in": {"input": "growler/alignments"},
                "position": {"top": 400, "left": 900},
            },
        },
        "outputs": {
            "cleaned_chains": {"outputSource": "chainstitchid_clean/output"},
            "rbest_chains": {"outputSource": "rb_sort2/out"},
            "pairwise_axt": {"outputSource": "axt_concat/out_file1"},
        },
    }


# ------------------------------------------------------------------------ the import size guard

#: zlib bytes at which a single annotation is worth a note, and at which it is a problem.
#:
#: ⛔ usegalaxy.org answers `POST /api/workflows` with `500 {"err_msg": "Uncaught exception in
#: exposed API method:"}` AND NO TRACEBACK once an annotation gets too big. gxformat2 converts the
#: same file locally without complaint and `planemo workflow_lint` passes, so nothing in this
#: repository's checks would notice -- an un-importable workflow reaches main unseen, which has
#: already happened once in a sibling repository.
#:
#: ⚠ THE LIMIT TRACKS COMPRESSED SIZE, SO LENGTH IS THE WRONG THING TO MEASURE. Measured on
#: usegalaxy.org 26.1 varying only the top-level doc: 4,200 characters of `'a'` compress to 28
#: bytes and import fine; 3,000 characters of base64 compress to 2,290 and 500. A bisect over it
#: looks incoherent -- one added space flips 200 to 500 -- because the trigger is a threshold on a
#: derived size, not an offending substring.
ANNOTATION_NOTE_BYTES = 1_600
ANNOTATION_PROBLEM_BYTES = 1_900


def annotation_sizes(document: dict) -> list[tuple[int, str, int]]:
    """`(zlib bytes, where, characters)` for every annotation in a workflow, largest first.

    Every `doc` is its own annotation and each is capped separately, so the SUM is not the thing to
    measure either -- a document of many small docs is fine and one long step doc is not.
    """
    items = [("<workflow doc>", document.get("doc", ""))]
    for section in ("inputs", "steps", "outputs"):
        for name, value in (document.get(section) or {}).items():
            if isinstance(value, dict):
                items.append((f"{section[:-1]} {name}", value.get("doc", "")))
    sized = [(len(zlib.compress((text or "").encode())), where, len(text or "")) for where, text in items]
    return sorted(sized, reverse=True)


def annotation_complaints(document: dict, label: str) -> list[str]:
    """Anything at or over the problem threshold, as complaints. Empty means it should import."""
    return [
        f"{label}: {where} is {size:,} zlib bytes ({chars:,} chars) -- at or over the "
        f"{ANNOTATION_PROBLEM_BYTES:,}-byte import limit; usegalaxy.org will 500 with no traceback"
        for size, where, chars in annotation_sizes(document)
        if size >= ANNOTATION_PROBLEM_BYTES
    ]


def render(growler: dict) -> str:
    return BANNER + yaml.safe_dump(build(growler), sort_keys=False, width=100, allow_unicode=True)


def render_pair(growler: dict) -> str:
    return BANNER + yaml.safe_dump(build_pair(growler), sort_keys=False, width=100, allow_unicode=True)


def self_test() -> int:
    failures = []

    def check(label, got, want):
        if got != want:
            print(f"not ok - {label}\n     got: {got}\nexpected: {want}")
            failures.append(label)
        else:
            print(f"ok - {label}")

    child = {"class": "GalaxyWorkflow", "label": "kid",
             "inputs": {"target_fasta": {"type": "data"}, "query_fasta": {"type": "data"},
                        "scores": {"type": "data", "optional": True},
                        "output_format": {"type": "text", "default": "axt"}},
             "outputs": {"alignments": {"outputSource": "x/out"}}, "steps": {}}
    panel = build(child)

    check("the child is inlined, not referenced", panel["steps"]["growler"]["run"], child)
    check("self-pairs are filtered out of both arms",
          sorted(k for k, v in panel["steps"].items() if v.get("tool_id") == "__FILTER_FROM_FILE__"),
          ["queries", "targets"])
    # ▶ output_a must reach the TARGET and output_b the QUERY. Crossing them silently aligns every
    # pair backwards: the run succeeds, the chains are all reversed, and nothing raises.
    check("output_a drives target", panel["steps"]["targets"]["in"]["input"], "pairs/output_a")
    check("output_b drives query", panel["steps"]["queries"]["in"]["input"], "pairs/output_b")
    # ⛔ THE FILTER DIRECTION. `self_pairs` lists the diagonal, so the diagonal must be REMOVED.
    # `remove_if_absent` keeps only what the file names -- i.e. only the self-pairs -- which is the
    # exact inverse, runs perfectly happily, and aligns every genome against itself. This assertion
    # exists because the first version of this file had it backwards.
    for arm in ("targets", "queries"):
        check(f"{arm}: the diagonal is removed, not retained",
              panel["steps"][arm]["state"]["how"]["how_filter"], "remove_if_present")

    check("growler takes the filtered lists, not the raw cross product",
          [panel["steps"]["growler"]["in"]["target_fasta"], panel["steps"]["growler"]["in"]["query_fasta"]],
          ["targets/output_filtered", "queries/output_filtered"])
    # ⛔ THE FORMAT MUST REACH THE CHILD FROM THE PANEL, NOT FROM THE CHILD'S OWN DEFAULT. Drop
    # this connection and every pair silently falls back to whatever growler.gxwf.yml defaults to
    # -- which is a perfectly valid run, in the wrong format, discovered at the chain step.
    check("the panel drives the child's output format",
          panel["steps"]["growler"]["in"].get("output_format"), "output_format")
    check("  and the panel's own default is the chain path's format",
          panel["inputs"]["output_format"]["default"], "axt")

    # every name the panel connects to must exist in the child, or the import binds nothing
    for slot in ("target_fasta", "query_fasta", "scores", "output_format"):
        check(f"child declares input {slot}", slot in child["inputs"], True)
    check("child declares the output the panel exports",
          panel["outputs"]["alignments"]["outputSource"].split("/")[1] in child["outputs"], True)
    check("render round-trips through yaml",
          yaml.safe_load(render(child))["steps"]["growler"]["run"]["label"], "kid")

    # ------------------------------------------------------------------------------ the wrapper
    pair = build_pair(child)
    check("the wrapper inlines the child too", pair["steps"]["growler"]["run"], child)
    check("the wrapper exports exactly what WF-C declares",
          sorted(pair["outputs"]), ["cleaned_chains", "pairwise_axt", "rbest_chains"])

    # ⛔ THE COLLAPSE MUST EXIST ON BOTH BRANCHES. Either one left mapped hands the caller a
    # collection where WF-C declares a dataset, and the caller -- WF-C -- then sees list:list,
    # which is the single property this document exists to prevent. The plan's own §4 diagram
    # omitted the AXT one, so this is asserted rather than trusted.
    check("the chain branch collapses at chainMergeSort",
          pair["steps"]["chainmergesort"]["in"]["in_chains"], "axtchain/out")
    check("the axt branch collapses too, by concatenation",
          pair["steps"]["axt_concat"]["in"]["input"], "growler/alignments")
    for name, source in pair["outputs"].items():
        collapsed = source["outputSource"].split("/")[0] not in ("growler", "axtchain")
        check(f"  {name} comes from a collapsed step", collapsed, True)

    # ⛔ chainMergeSort REPLACES the chainSort WF-C runs here; it must not be reinstated between
    # them, because its output is already score-ordered and that is chainPreNet's precondition.
    check("no chainSort sits between the merge and chainPreNet",
          pair["steps"]["chainprenet"]["in"]["in_chain"], "chainmergesort/out")

    # ⛔ THE RECIPROCAL-BEST ARM SWAPS BACK. Without rb_swap2/rb_sort2 the rbest chains are
    # QUERY-referenced and every consumer reads them as target-referenced with nothing raising.
    # §4's diagram omitted both steps, and the acceptance test as written could not have caught it.
    check("rbest is swapped back before it is exported",
          [pair["steps"]["rb_swap2"]["in"]["in_chain"], pair["outputs"]["rbest_chains"]["outputSource"]],
          ["rb_stitch/output", "rb_sort2/out"])
    # ⚠ and the rbest net runs in the SWAPPED frame, so its sizes files are the other way round
    check("the rbest net takes the sizes swapped",
          [pair["steps"]["rb_net"]["in"]["target_reference_index_source|in_tar_ref_index"],
           pair["steps"]["chainnet"]["in"]["target_reference_index_source|in_tar_ref_index"]],
          ["query_sizes", "target_sizes"])

    check("the wrapper's format default is the chain path's format",
          pair["inputs"]["output_format"]["default"], "axt")
    check("  and it drives the child rather than letting it default",
          pair["steps"]["growler"]["in"]["output_format"], "output_format")
    check("WF-C's gap model is carried over, not defaulted",
          pair["steps"]["axtchain"]["state"]["linear_gap_options"]["linear_gap"], "loose")

    # ⛔ THE STITCH STEPS MUST NAME THE UDT, NOT THE CLASSIC ID. `chainStitchId` is what WF-C's
    # classic edition says and it looks more correct, which is exactly why this is pinned: that id
    # resolves on neither usegalaxy.org nor vgp, because the shed wrapper was never published.
    # Both steps, because only one of them is the exported deliverable and a half-fixed pair would
    # still lint, still import, and fail at the second job.
    check("both stitch steps name the UDT that actually resolves",
          [pair["steps"]["chainstitchid_clean"]["tool_id"], pair["steps"]["rb_stitch"]["tool_id"]],
          ["brc-chain-stitch-id", "brc-chain-stitch-id"])
    check("the wrapper renders", yaml.safe_load(render_pair(child))["label"],
          "Growler pair (one genome pair, through chains)")

    # ------------------------------------------------------------------- the import size guard
    # ⛔ AND IT MUST BE ABLE TO FIRE. A guard that has never rejected anything is a guard nobody
    # has tested. Incompressible text is used because the threshold is on COMPRESSED size: 3,000
    # characters of base64 crossed it on usegalaxy.org while 4,200 characters of "a" did not.
    import base64
    import os

    incompressible = base64.b64encode(os.urandom(3000)).decode()
    check("a real document passes the guard", annotation_complaints(build_pair(child), "x"), [])
    fat = {"doc": incompressible, "steps": {}, "inputs": {}}
    check("an over-long workflow doc IS rejected", len(annotation_complaints(fat, "x")), 1)
    fat_step = {"doc": "", "steps": {"s": {"doc": incompressible}}, "inputs": {}}
    check("  and so is an over-long STEP doc, which is capped separately",
          len(annotation_complaints(fat_step, "x")), 1)
    # ⚠ LENGTH IS THE WRONG MEASURE, and a guard written on characters would pass this and fail
    # the one above -- 4,200 compressible characters import fine.
    check("  while 4,200 compressible characters do NOT trip it",
          annotation_complaints({"doc": "a" * 4200, "steps": {}, "inputs": {}}, "x"), [])
    check("sizes are reported largest first",
          annotation_sizes({"doc": "aaa", "steps": {"s": {"doc": incompressible}}, "inputs": {}})[0][1],
          "step s")

    if failures:
        print(f"\n{len(failures)} test(s) failed")
        return 1
    print("\nall tests passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    growler = yaml.safe_load(GROWLER.read_text())
    documents = [(PAIR, render_pair(growler)), (PANEL, render(growler))]
    # ⛔ CHECKED ON EVERY RUN, INCLUDING A PLAIN WRITE. An over-long annotation does not fail here,
    # it fails at `POST /api/workflows` with a 500 and no traceback -- long after this script, and
    # after planemo and gxformat2 have both passed it.
    complaints = [c for path, rendered in documents
                  for c in annotation_complaints(yaml.safe_load(rendered), path.name)]
    if complaints:
        for complaint in complaints:
            print(f"⛔ {complaint}", file=sys.stderr)
        print("Shorten the annotation, or move the long explanation into the tool's own help, "
              "which has no such cap.", file=sys.stderr)
        return 1

    if args.check:
        stale = 0
        for path, rendered in documents:
            if not path.exists():
                print(f"{path.name} is missing; run ./assemble.py", file=sys.stderr)
                stale += 1
            elif path.read_text() != rendered:
                print(f"{path.name} is stale; run ./assemble.py", file=sys.stderr)
                stale += 1
            else:
                print(f"{path.name} is current")
        return 1 if stale else 0

    for path, rendered in documents:
        path.write_text(rendered)
        biggest = annotation_sizes(yaml.safe_load(rendered))[0]
        print(f"wrote {path.name} ({len(rendered.splitlines())} lines; "
              f"largest annotation {biggest[0]:,} zlib bytes, {biggest[1]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
